/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package SendOtpService.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SendDb service. Represents a row in the &quot;FOO_SendDb&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>SendOtpService.model.impl.SendDbModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>SendOtpService.model.impl.SendDbImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SendDb
 * @generated
 */
@ProviderType
public interface SendDbModel extends BaseModel<SendDb>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a send db model instance should use the {@link SendDb} interface instead.
	 */

	/**
	 * Returns the primary key of this send db.
	 *
	 * @return the primary key of this send db
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this send db.
	 *
	 * @param primaryKey the primary key of this send db
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this send db.
	 *
	 * @return the uuid of this send db
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this send db.
	 *
	 * @param uuid the uuid of this send db
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the send ID of this send db.
	 *
	 * @return the send ID of this send db
	 */
	public long getSendId();

	/**
	 * Sets the send ID of this send db.
	 *
	 * @param sendId the send ID of this send db
	 */
	public void setSendId(long sendId);

	/**
	 * Returns the company ID of this send db.
	 *
	 * @return the company ID of this send db
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this send db.
	 *
	 * @param companyId the company ID of this send db
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this send db.
	 *
	 * @return the user ID of this send db
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this send db.
	 *
	 * @param userId the user ID of this send db
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this send db.
	 *
	 * @return the user uuid of this send db
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this send db.
	 *
	 * @param userUuid the user uuid of this send db
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this send db.
	 *
	 * @return the user name of this send db
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this send db.
	 *
	 * @param userName the user name of this send db
	 */
	public void setUserName(String userName);

	/**
	 * Returns the mobile number of this send db.
	 *
	 * @return the mobile number of this send db
	 */
	public long getMobileNumber();

	/**
	 * Sets the mobile number of this send db.
	 *
	 * @param mobileNumber the mobile number of this send db
	 */
	public void setMobileNumber(long mobileNumber);

	/**
	 * Returns the name of this send db.
	 *
	 * @return the name of this send db
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this send db.
	 *
	 * @param Name the name of this send db
	 */
	public void setName(String Name);

	@Override
	public SendDb cloneWithOriginalValues();

}