/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.docter.service.model.impl;

import com.docter.service.model.Docters;
import com.docter.service.service.DoctersLocalServiceUtil;

/**
 * The extended model base implementation for the Docters service. Represents a row in the &quot;DOC_Docters&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DoctersImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DoctersImpl
 * @see Docters
 * @generated
 */
public abstract class DoctersBaseImpl
	extends DoctersModelImpl implements Docters {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a docters model instance should use the <code>Docters</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			DoctersLocalServiceUtil.addDocters(this);
		}
		else {
			DoctersLocalServiceUtil.updateDocters(this);
		}
	}

}