/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.prime.data.service.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.prime.data.service.model.InterviewName;
import com.prime.data.service.service.InterviewNameLocalService;
import com.prime.data.service.service.InterviewNameLocalServiceUtil;
import com.prime.data.service.service.persistence.CandidateStatusPersistence;
import com.prime.data.service.service.persistence.CurrJobTitlePersistence;
import com.prime.data.service.service.persistence.DocumentMapperPersistence;
import com.prime.data.service.service.persistence.HighQualHeldPersistence;
import com.prime.data.service.service.persistence.IndustryPersistence;
import com.prime.data.service.service.persistence.InterviewNamePersistence;
import com.prime.data.service.service.persistence.JobOpeningStatusPersistence;
import com.prime.data.service.service.persistence.JobTypePersistence;
import com.prime.data.service.service.persistence.MainTablePersistence;
import com.prime.data.service.service.persistence.NamePrefixPersistence;
import com.prime.data.service.service.persistence.PriorityPersistence;
import com.prime.data.service.service.persistence.ProjectStatusPersistence;
import com.prime.data.service.service.persistence.SalaryRangePersistence;
import com.prime.data.service.service.persistence.SalesStagePersistence;
import com.prime.data.service.service.persistence.SkillSetPersistence;
import com.prime.data.service.service.persistence.SourceByPersistence;
import com.prime.data.service.service.persistence.WorkExperiencePersistence;
import com.prime.data.service.service.persistence.WorkTypePersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the interview name local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.prime.data.service.service.impl.InterviewNameLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.prime.data.service.service.impl.InterviewNameLocalServiceImpl
 * @generated
 */
public abstract class InterviewNameLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, InterviewNameLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>InterviewNameLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>InterviewNameLocalServiceUtil</code>.
	 */

	/**
	 * Adds the interview name to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect InterviewNameLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param interviewName the interview name
	 * @return the interview name that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public InterviewName addInterviewName(InterviewName interviewName) {
		interviewName.setNew(true);

		return interviewNamePersistence.update(interviewName);
	}

	/**
	 * Creates a new interview name with the primary key. Does not add the interview name to the database.
	 *
	 * @param interviewNameId the primary key for the new interview name
	 * @return the new interview name
	 */
	@Override
	@Transactional(enabled = false)
	public InterviewName createInterviewName(long interviewNameId) {
		return interviewNamePersistence.create(interviewNameId);
	}

	/**
	 * Deletes the interview name with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect InterviewNameLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param interviewNameId the primary key of the interview name
	 * @return the interview name that was removed
	 * @throws PortalException if a interview name with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public InterviewName deleteInterviewName(long interviewNameId)
		throws PortalException {

		return interviewNamePersistence.remove(interviewNameId);
	}

	/**
	 * Deletes the interview name from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect InterviewNameLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param interviewName the interview name
	 * @return the interview name that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public InterviewName deleteInterviewName(InterviewName interviewName) {
		return interviewNamePersistence.remove(interviewName);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return interviewNamePersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			InterviewName.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return interviewNamePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.prime.data.service.model.impl.InterviewNameModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return interviewNamePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.prime.data.service.model.impl.InterviewNameModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return interviewNamePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return interviewNamePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return interviewNamePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public InterviewName fetchInterviewName(long interviewNameId) {
		return interviewNamePersistence.fetchByPrimaryKey(interviewNameId);
	}

	/**
	 * Returns the interview name with the primary key.
	 *
	 * @param interviewNameId the primary key of the interview name
	 * @return the interview name
	 * @throws PortalException if a interview name with the primary key could not be found
	 */
	@Override
	public InterviewName getInterviewName(long interviewNameId)
		throws PortalException {

		return interviewNamePersistence.findByPrimaryKey(interviewNameId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(interviewNameLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(InterviewName.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("interviewNameId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			interviewNameLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(InterviewName.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"interviewNameId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(interviewNameLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(InterviewName.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("interviewNameId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return interviewNamePersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return interviewNameLocalService.deleteInterviewName(
			(InterviewName)persistedModel);
	}

	@Override
	public BasePersistence<InterviewName> getBasePersistence() {
		return interviewNamePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return interviewNamePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the interview names.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.prime.data.service.model.impl.InterviewNameModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of interview names
	 * @param end the upper bound of the range of interview names (not inclusive)
	 * @return the range of interview names
	 */
	@Override
	public List<InterviewName> getInterviewNames(int start, int end) {
		return interviewNamePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of interview names.
	 *
	 * @return the number of interview names
	 */
	@Override
	public int getInterviewNamesCount() {
		return interviewNamePersistence.countAll();
	}

	/**
	 * Updates the interview name in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect InterviewNameLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param interviewName the interview name
	 * @return the interview name that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public InterviewName updateInterviewName(InterviewName interviewName) {
		return interviewNamePersistence.update(interviewName);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			InterviewNameLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		interviewNameLocalService = (InterviewNameLocalService)aopProxy;

		_setLocalServiceUtilService(interviewNameLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return InterviewNameLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return InterviewName.class;
	}

	protected String getModelClassName() {
		return InterviewName.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = interviewNamePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		InterviewNameLocalService interviewNameLocalService) {

		try {
			Field field = InterviewNameLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, interviewNameLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected CandidateStatusPersistence candidateStatusPersistence;

	@Reference
	protected CurrJobTitlePersistence currJobTitlePersistence;

	@Reference
	protected DocumentMapperPersistence documentMapperPersistence;

	@Reference
	protected HighQualHeldPersistence highQualHeldPersistence;

	@Reference
	protected IndustryPersistence industryPersistence;

	protected InterviewNameLocalService interviewNameLocalService;

	@Reference
	protected InterviewNamePersistence interviewNamePersistence;

	@Reference
	protected JobOpeningStatusPersistence jobOpeningStatusPersistence;

	@Reference
	protected JobTypePersistence jobTypePersistence;

	@Reference
	protected MainTablePersistence mainTablePersistence;

	@Reference
	protected NamePrefixPersistence namePrefixPersistence;

	@Reference
	protected PriorityPersistence priorityPersistence;

	@Reference
	protected ProjectStatusPersistence projectStatusPersistence;

	@Reference
	protected SalaryRangePersistence salaryRangePersistence;

	@Reference
	protected SalesStagePersistence salesStagePersistence;

	@Reference
	protected SkillSetPersistence skillSetPersistence;

	@Reference
	protected SourceByPersistence sourceByPersistence;

	@Reference
	protected WorkExperiencePersistence workExperiencePersistence;

	@Reference
	protected WorkTypePersistence workTypePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}