/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.intranet.service.base;

import com.intranet.model.ComplaintBox;
import com.intranet.service.ComplaintBoxLocalService;
import com.intranet.service.ComplaintBoxLocalServiceUtil;
import com.intranet.service.persistence.BillclaimPersistence;
import com.intranet.service.persistence.ComplaintBoxPersistence;
import com.intranet.service.persistence.EducationDetailsPersistence;
import com.intranet.service.persistence.EmployeeDetailsPersistence;
import com.intranet.service.persistence.ExperienceDetailsPersistence;
import com.intranet.service.persistence.GraduationPersistence;
import com.intranet.service.persistence.SpecializationPersistence;
import com.intranet.service.persistence.skillsPersistence;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the complaint box local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.intranet.service.impl.ComplaintBoxLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.intranet.service.impl.ComplaintBoxLocalServiceImpl
 * @generated
 */
public abstract class ComplaintBoxLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, ComplaintBoxLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ComplaintBoxLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>ComplaintBoxLocalServiceUtil</code>.
	 */

	/**
	 * Adds the complaint box to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ComplaintBoxLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param complaintBox the complaint box
	 * @return the complaint box that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ComplaintBox addComplaintBox(ComplaintBox complaintBox) {
		complaintBox.setNew(true);

		return complaintBoxPersistence.update(complaintBox);
	}

	/**
	 * Creates a new complaint box with the primary key. Does not add the complaint box to the database.
	 *
	 * @param fooId the primary key for the new complaint box
	 * @return the new complaint box
	 */
	@Override
	@Transactional(enabled = false)
	public ComplaintBox createComplaintBox(long fooId) {
		return complaintBoxPersistence.create(fooId);
	}

	/**
	 * Deletes the complaint box with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ComplaintBoxLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param fooId the primary key of the complaint box
	 * @return the complaint box that was removed
	 * @throws PortalException if a complaint box with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ComplaintBox deleteComplaintBox(long fooId) throws PortalException {
		return complaintBoxPersistence.remove(fooId);
	}

	/**
	 * Deletes the complaint box from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ComplaintBoxLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param complaintBox the complaint box
	 * @return the complaint box that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ComplaintBox deleteComplaintBox(ComplaintBox complaintBox) {
		return complaintBoxPersistence.remove(complaintBox);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return complaintBoxPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			ComplaintBox.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return complaintBoxPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.intranet.model.impl.ComplaintBoxModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return complaintBoxPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.intranet.model.impl.ComplaintBoxModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return complaintBoxPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return complaintBoxPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return complaintBoxPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public ComplaintBox fetchComplaintBox(long fooId) {
		return complaintBoxPersistence.fetchByPrimaryKey(fooId);
	}

	/**
	 * Returns the complaint box with the primary key.
	 *
	 * @param fooId the primary key of the complaint box
	 * @return the complaint box
	 * @throws PortalException if a complaint box with the primary key could not be found
	 */
	@Override
	public ComplaintBox getComplaintBox(long fooId) throws PortalException {
		return complaintBoxPersistence.findByPrimaryKey(fooId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(complaintBoxLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ComplaintBox.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("fooId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			complaintBoxLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(ComplaintBox.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("fooId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(complaintBoxLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ComplaintBox.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("fooId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return complaintBoxPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return complaintBoxLocalService.deleteComplaintBox(
			(ComplaintBox)persistedModel);
	}

	@Override
	public BasePersistence<ComplaintBox> getBasePersistence() {
		return complaintBoxPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return complaintBoxPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the complaint boxes.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.intranet.model.impl.ComplaintBoxModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of complaint boxes
	 * @param end the upper bound of the range of complaint boxes (not inclusive)
	 * @return the range of complaint boxes
	 */
	@Override
	public List<ComplaintBox> getComplaintBoxes(int start, int end) {
		return complaintBoxPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of complaint boxes.
	 *
	 * @return the number of complaint boxes
	 */
	@Override
	public int getComplaintBoxesCount() {
		return complaintBoxPersistence.countAll();
	}

	/**
	 * Updates the complaint box in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ComplaintBoxLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param complaintBox the complaint box
	 * @return the complaint box that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ComplaintBox updateComplaintBox(ComplaintBox complaintBox) {
		return complaintBoxPersistence.update(complaintBox);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			ComplaintBoxLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		complaintBoxLocalService = (ComplaintBoxLocalService)aopProxy;

		_setLocalServiceUtilService(complaintBoxLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ComplaintBoxLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ComplaintBox.class;
	}

	protected String getModelClassName() {
		return ComplaintBox.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = complaintBoxPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		ComplaintBoxLocalService complaintBoxLocalService) {

		try {
			Field field = ComplaintBoxLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, complaintBoxLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected BillclaimPersistence billclaimPersistence;

	protected ComplaintBoxLocalService complaintBoxLocalService;

	@Reference
	protected ComplaintBoxPersistence complaintBoxPersistence;

	@Reference
	protected EducationDetailsPersistence educationDetailsPersistence;

	@Reference
	protected EmployeeDetailsPersistence employeeDetailsPersistence;

	@Reference
	protected ExperienceDetailsPersistence experienceDetailsPersistence;

	@Reference
	protected GraduationPersistence graduationPersistence;

	@Reference
	protected skillsPersistence skillsPersistence;

	@Reference
	protected SpecializationPersistence specializationPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}