/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.intranet.service.base;

import com.intranet.model.Graduation;
import com.intranet.service.GraduationLocalService;
import com.intranet.service.GraduationLocalServiceUtil;
import com.intranet.service.persistence.BillclaimPersistence;
import com.intranet.service.persistence.ComplaintBoxPersistence;
import com.intranet.service.persistence.EducationDetailsPersistence;
import com.intranet.service.persistence.EmployeeDetailsPersistence;
import com.intranet.service.persistence.ExperienceDetailsPersistence;
import com.intranet.service.persistence.GraduationPersistence;
import com.intranet.service.persistence.SpecializationPersistence;
import com.intranet.service.persistence.skillsPersistence;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the graduation local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.intranet.service.impl.GraduationLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.intranet.service.impl.GraduationLocalServiceImpl
 * @generated
 */
public abstract class GraduationLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, GraduationLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>GraduationLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>GraduationLocalServiceUtil</code>.
	 */

	/**
	 * Adds the graduation to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect GraduationLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param graduation the graduation
	 * @return the graduation that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Graduation addGraduation(Graduation graduation) {
		graduation.setNew(true);

		return graduationPersistence.update(graduation);
	}

	/**
	 * Creates a new graduation with the primary key. Does not add the graduation to the database.
	 *
	 * @param graduationCode the primary key for the new graduation
	 * @return the new graduation
	 */
	@Override
	@Transactional(enabled = false)
	public Graduation createGraduation(String graduationCode) {
		return graduationPersistence.create(graduationCode);
	}

	/**
	 * Deletes the graduation with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect GraduationLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param graduationCode the primary key of the graduation
	 * @return the graduation that was removed
	 * @throws PortalException if a graduation with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Graduation deleteGraduation(String graduationCode)
		throws PortalException {

		return graduationPersistence.remove(graduationCode);
	}

	/**
	 * Deletes the graduation from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect GraduationLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param graduation the graduation
	 * @return the graduation that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Graduation deleteGraduation(Graduation graduation) {
		return graduationPersistence.remove(graduation);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return graduationPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			Graduation.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return graduationPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.intranet.model.impl.GraduationModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return graduationPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.intranet.model.impl.GraduationModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return graduationPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return graduationPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return graduationPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public Graduation fetchGraduation(String graduationCode) {
		return graduationPersistence.fetchByPrimaryKey(graduationCode);
	}

	/**
	 * Returns the graduation with the primary key.
	 *
	 * @param graduationCode the primary key of the graduation
	 * @return the graduation
	 * @throws PortalException if a graduation with the primary key could not be found
	 */
	@Override
	public Graduation getGraduation(String graduationCode)
		throws PortalException {

		return graduationPersistence.findByPrimaryKey(graduationCode);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return graduationPersistence.create((String)primaryKeyObj);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return graduationLocalService.deleteGraduation(
			(Graduation)persistedModel);
	}

	@Override
	public BasePersistence<Graduation> getBasePersistence() {
		return graduationPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return graduationPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the graduations.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.intranet.model.impl.GraduationModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of graduations
	 * @param end the upper bound of the range of graduations (not inclusive)
	 * @return the range of graduations
	 */
	@Override
	public List<Graduation> getGraduations(int start, int end) {
		return graduationPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of graduations.
	 *
	 * @return the number of graduations
	 */
	@Override
	public int getGraduationsCount() {
		return graduationPersistence.countAll();
	}

	/**
	 * Updates the graduation in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect GraduationLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param graduation the graduation
	 * @return the graduation that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Graduation updateGraduation(Graduation graduation) {
		return graduationPersistence.update(graduation);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			GraduationLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		graduationLocalService = (GraduationLocalService)aopProxy;

		_setLocalServiceUtilService(graduationLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return GraduationLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Graduation.class;
	}

	protected String getModelClassName() {
		return Graduation.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = graduationPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		GraduationLocalService graduationLocalService) {

		try {
			Field field = GraduationLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, graduationLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected BillclaimPersistence billclaimPersistence;

	@Reference
	protected ComplaintBoxPersistence complaintBoxPersistence;

	@Reference
	protected EducationDetailsPersistence educationDetailsPersistence;

	@Reference
	protected EmployeeDetailsPersistence employeeDetailsPersistence;

	@Reference
	protected ExperienceDetailsPersistence experienceDetailsPersistence;

	protected GraduationLocalService graduationLocalService;

	@Reference
	protected GraduationPersistence graduationPersistence;

	@Reference
	protected skillsPersistence skillsPersistence;

	@Reference
	protected SpecializationPersistence specializationPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}