/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.candidate.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CandidateInfo service. Represents a row in the &quot;RMS_CandidateInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.candidate.service.model.impl.CandidateInfoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.candidate.service.model.impl.CandidateInfoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CandidateInfo
 * @generated
 */
@ProviderType
public interface CandidateInfoModel
	extends BaseModel<CandidateInfo>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a candidate info model instance should use the {@link CandidateInfo} interface instead.
	 */

	/**
	 * Returns the primary key of this candidate info.
	 *
	 * @return the primary key of this candidate info
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this candidate info.
	 *
	 * @param primaryKey the primary key of this candidate info
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this candidate info.
	 *
	 * @return the uuid of this candidate info
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this candidate info.
	 *
	 * @param uuid the uuid of this candidate info
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the candidate ID of this candidate info.
	 *
	 * @return the candidate ID of this candidate info
	 */
	public long getCandidateId();

	/**
	 * Sets the candidate ID of this candidate info.
	 *
	 * @param candidateId the candidate ID of this candidate info
	 */
	public void setCandidateId(long candidateId);

	/**
	 * Returns the first name of this candidate info.
	 *
	 * @return the first name of this candidate info
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this candidate info.
	 *
	 * @param firstName the first name of this candidate info
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this candidate info.
	 *
	 * @return the last name of this candidate info
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this candidate info.
	 *
	 * @param lastName the last name of this candidate info
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the email of this candidate info.
	 *
	 * @return the email of this candidate info
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this candidate info.
	 *
	 * @param email the email of this candidate info
	 */
	public void setEmail(String email);

	/**
	 * Returns the secondary email of this candidate info.
	 *
	 * @return the secondary email of this candidate info
	 */
	@AutoEscape
	public String getSecondaryEmail();

	/**
	 * Sets the secondary email of this candidate info.
	 *
	 * @param secondaryEmail the secondary email of this candidate info
	 */
	public void setSecondaryEmail(String secondaryEmail);

	/**
	 * Returns the mobile number of this candidate info.
	 *
	 * @return the mobile number of this candidate info
	 */
	@AutoEscape
	public String getMobileNumber();

	/**
	 * Sets the mobile number of this candidate info.
	 *
	 * @param mobileNumber the mobile number of this candidate info
	 */
	public void setMobileNumber(String mobileNumber);

	/**
	 * Returns the street of this candidate info.
	 *
	 * @return the street of this candidate info
	 */
	@AutoEscape
	public String getStreet();

	/**
	 * Sets the street of this candidate info.
	 *
	 * @param street the street of this candidate info
	 */
	public void setStreet(String street);

	/**
	 * Returns the country of this candidate info.
	 *
	 * @return the country of this candidate info
	 */
	@AutoEscape
	public String getCountry();

	/**
	 * Sets the country of this candidate info.
	 *
	 * @param country the country of this candidate info
	 */
	public void setCountry(String country);

	/**
	 * Returns the city of this candidate info.
	 *
	 * @return the city of this candidate info
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this candidate info.
	 *
	 * @param city the city of this candidate info
	 */
	public void setCity(String city);

	/**
	 * Returns the state of this candidate info.
	 *
	 * @return the state of this candidate info
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this candidate info.
	 *
	 * @param state the state of this candidate info
	 */
	public void setState(String state);

	/**
	 * Returns the zip code of this candidate info.
	 *
	 * @return the zip code of this candidate info
	 */
	@AutoEscape
	public String getZipCode();

	/**
	 * Sets the zip code of this candidate info.
	 *
	 * @param zipCode the zip code of this candidate info
	 */
	public void setZipCode(String zipCode);

	/**
	 * Returns the house number of this candidate info.
	 *
	 * @return the house number of this candidate info
	 */
	@AutoEscape
	public String getHouseNumber();

	/**
	 * Sets the house number of this candidate info.
	 *
	 * @param houseNumber the house number of this candidate info
	 */
	public void setHouseNumber(String houseNumber);

	/**
	 * Returns the website of this candidate info.
	 *
	 * @return the website of this candidate info
	 */
	@AutoEscape
	public String getWebsite();

	/**
	 * Sets the website of this candidate info.
	 *
	 * @param website the website of this candidate info
	 */
	public void setWebsite(String website);

	/**
	 * Returns the company ID of this candidate info.
	 *
	 * @return the company ID of this candidate info
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this candidate info.
	 *
	 * @param companyId the company ID of this candidate info
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this candidate info.
	 *
	 * @return the user ID of this candidate info
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this candidate info.
	 *
	 * @param userId the user ID of this candidate info
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this candidate info.
	 *
	 * @return the user uuid of this candidate info
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this candidate info.
	 *
	 * @param userUuid the user uuid of this candidate info
	 */
	public void setUserUuid(String userUuid);

	@Override
	public CandidateInfo cloneWithOriginalValues();

}