/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.intranet.model.impl;

import com.intranet.model.Graduation;
import com.intranet.model.GraduationModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Graduation service. Represents a row in the &quot;INTRANET_Graduation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>GraduationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GraduationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GraduationImpl
 * @generated
 */
public class GraduationModelImpl
	extends BaseModelImpl<Graduation> implements GraduationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a graduation model instance should use the <code>Graduation</code> interface instead.
	 */
	public static final String TABLE_NAME = "INTRANET_Graduation";

	public static final Object[][] TABLE_COLUMNS = {
		{"graduationCode", Types.VARCHAR}, {"graduationName", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("graduationCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("graduationName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table INTRANET_Graduation (graduationCode VARCHAR(75) not null primary key,graduationName VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table INTRANET_Graduation";

	public static final String ORDER_BY_JPQL =
		" ORDER BY graduation.graduationCode ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY INTRANET_Graduation.graduationCode ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GRADUATIONCODE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public GraduationModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _graduationCode;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setGraduationCode(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _graduationCode;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return Graduation.class;
	}

	@Override
	public String getModelClassName() {
		return Graduation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Graduation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Graduation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Graduation, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Graduation)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Graduation, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Graduation, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Graduation)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Graduation, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Graduation, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Graduation, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Graduation, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Graduation, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Graduation, Object>>();
		Map<String, BiConsumer<Graduation, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Graduation, ?>>();

		attributeGetterFunctions.put(
			"graduationCode", Graduation::getGraduationCode);
		attributeSetterBiConsumers.put(
			"graduationCode",
			(BiConsumer<Graduation, String>)Graduation::setGraduationCode);
		attributeGetterFunctions.put(
			"graduationName", Graduation::getGraduationName);
		attributeSetterBiConsumers.put(
			"graduationName",
			(BiConsumer<Graduation, String>)Graduation::setGraduationName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getGraduationCode() {
		if (_graduationCode == null) {
			return "";
		}
		else {
			return _graduationCode;
		}
	}

	@Override
	public void setGraduationCode(String graduationCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_graduationCode = graduationCode;
	}

	@Override
	public String getGraduationName() {
		if (_graduationName == null) {
			return "";
		}
		else {
			return _graduationName;
		}
	}

	@Override
	public void setGraduationName(String graduationName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_graduationName = graduationName;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public Graduation toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Graduation>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GraduationImpl graduationImpl = new GraduationImpl();

		graduationImpl.setGraduationCode(getGraduationCode());
		graduationImpl.setGraduationName(getGraduationName());

		graduationImpl.resetOriginalValues();

		return graduationImpl;
	}

	@Override
	public Graduation cloneWithOriginalValues() {
		GraduationImpl graduationImpl = new GraduationImpl();

		graduationImpl.setGraduationCode(
			this.<String>getColumnOriginalValue("graduationCode"));
		graduationImpl.setGraduationName(
			this.<String>getColumnOriginalValue("graduationName"));

		return graduationImpl;
	}

	@Override
	public int compareTo(Graduation graduation) {
		String primaryKey = graduation.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Graduation)) {
			return false;
		}

		Graduation graduation = (Graduation)object;

		String primaryKey = graduation.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Graduation> toCacheModel() {
		GraduationCacheModel graduationCacheModel = new GraduationCacheModel();

		graduationCacheModel.graduationCode = getGraduationCode();

		String graduationCode = graduationCacheModel.graduationCode;

		if ((graduationCode != null) && (graduationCode.length() == 0)) {
			graduationCacheModel.graduationCode = null;
		}

		graduationCacheModel.graduationName = getGraduationName();

		String graduationName = graduationCacheModel.graduationName;

		if ((graduationName != null) && (graduationName.length() == 0)) {
			graduationCacheModel.graduationName = null;
		}

		return graduationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Graduation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Graduation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Graduation, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Graduation)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Graduation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Graduation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Graduation, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Graduation)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Graduation>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Graduation.class, ModelWrapper.class);

	}

	private String _graduationCode;
	private String _graduationName;

	public <T> T getColumnValue(String columnName) {
		Function<Graduation, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Graduation)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("graduationCode", _graduationCode);
		_columnOriginalValues.put("graduationName", _graduationName);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("graduationCode", 1L);

		columnBitmasks.put("graduationName", 2L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Graduation _escapedModel;

}