/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.intranet.model.impl;

import com.intranet.model.skills;
import com.intranet.model.skillsModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the skills service. Represents a row in the &quot;INTRANET_skills&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>skillsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link skillsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see skillsImpl
 * @generated
 */
public class skillsModelImpl
	extends BaseModelImpl<skills> implements skillsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a skills model instance should use the <code>skills</code> interface instead.
	 */
	public static final String TABLE_NAME = "INTRANET_skills";

	public static final Object[][] TABLE_COLUMNS = {
		{"skillId", Types.BIGINT}, {"employeeID", Types.BIGINT},
		{"skill", Types.VARCHAR}, {"version", Types.VARCHAR},
		{"certification", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("skillId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("employeeID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("skill", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("version", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("certification", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table INTRANET_skills (skillId LONG not null primary key,employeeID LONG,skill VARCHAR(75) null,version VARCHAR(75) null,certification BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table INTRANET_skills";

	public static final String ORDER_BY_JPQL = " ORDER BY skills.skillId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY INTRANET_skills.skillId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SKILL_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SKILLID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public skillsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _skillId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSkillId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _skillId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return skills.class;
	}

	@Override
	public String getModelClassName() {
		return skills.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<skills, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<skills, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<skills, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((skills)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<skills, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<skills, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(skills)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<skills, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<skills, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<skills, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<skills, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<skills, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<skills, Object>>();
		Map<String, BiConsumer<skills, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<skills, ?>>();

		attributeGetterFunctions.put("skillId", skills::getSkillId);
		attributeSetterBiConsumers.put(
			"skillId", (BiConsumer<skills, Long>)skills::setSkillId);
		attributeGetterFunctions.put("employeeID", skills::getEmployeeID);
		attributeSetterBiConsumers.put(
			"employeeID", (BiConsumer<skills, Long>)skills::setEmployeeID);
		attributeGetterFunctions.put("skill", skills::getSkill);
		attributeSetterBiConsumers.put(
			"skill", (BiConsumer<skills, String>)skills::setSkill);
		attributeGetterFunctions.put("version", skills::getVersion);
		attributeSetterBiConsumers.put(
			"version", (BiConsumer<skills, String>)skills::setVersion);
		attributeGetterFunctions.put("certification", skills::getCertification);
		attributeSetterBiConsumers.put(
			"certification",
			(BiConsumer<skills, Boolean>)skills::setCertification);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getSkillId() {
		return _skillId;
	}

	@Override
	public void setSkillId(long skillId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_skillId = skillId;
	}

	@Override
	public long getEmployeeID() {
		return _employeeID;
	}

	@Override
	public void setEmployeeID(long employeeID) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeID = employeeID;
	}

	@Override
	public String getSkill() {
		if (_skill == null) {
			return "";
		}
		else {
			return _skill;
		}
	}

	@Override
	public void setSkill(String skill) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_skill = skill;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalSkill() {
		return getColumnOriginalValue("skill");
	}

	@Override
	public String getVersion() {
		if (_version == null) {
			return "";
		}
		else {
			return _version;
		}
	}

	@Override
	public void setVersion(String version) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_version = version;
	}

	@Override
	public boolean getCertification() {
		return _certification;
	}

	@Override
	public boolean isCertification() {
		return _certification;
	}

	@Override
	public void setCertification(boolean certification) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_certification = certification;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, skills.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public skills toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, skills>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		skillsImpl skillsImpl = new skillsImpl();

		skillsImpl.setSkillId(getSkillId());
		skillsImpl.setEmployeeID(getEmployeeID());
		skillsImpl.setSkill(getSkill());
		skillsImpl.setVersion(getVersion());
		skillsImpl.setCertification(isCertification());

		skillsImpl.resetOriginalValues();

		return skillsImpl;
	}

	@Override
	public skills cloneWithOriginalValues() {
		skillsImpl skillsImpl = new skillsImpl();

		skillsImpl.setSkillId(this.<Long>getColumnOriginalValue("skillId"));
		skillsImpl.setEmployeeID(
			this.<Long>getColumnOriginalValue("employeeID"));
		skillsImpl.setSkill(this.<String>getColumnOriginalValue("skill"));
		skillsImpl.setVersion(this.<String>getColumnOriginalValue("version"));
		skillsImpl.setCertification(
			this.<Boolean>getColumnOriginalValue("certification"));

		return skillsImpl;
	}

	@Override
	public int compareTo(skills skills) {
		long primaryKey = skills.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof skills)) {
			return false;
		}

		skills skills = (skills)object;

		long primaryKey = skills.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<skills> toCacheModel() {
		skillsCacheModel skillsCacheModel = new skillsCacheModel();

		skillsCacheModel.skillId = getSkillId();

		skillsCacheModel.employeeID = getEmployeeID();

		skillsCacheModel.skill = getSkill();

		String skill = skillsCacheModel.skill;

		if ((skill != null) && (skill.length() == 0)) {
			skillsCacheModel.skill = null;
		}

		skillsCacheModel.version = getVersion();

		String version = skillsCacheModel.version;

		if ((version != null) && (version.length() == 0)) {
			skillsCacheModel.version = null;
		}

		skillsCacheModel.certification = isCertification();

		return skillsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<skills, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<skills, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<skills, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((skills)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<skills, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<skills, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<skills, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((skills)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, skills>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					skills.class, ModelWrapper.class);

	}

	private long _skillId;
	private long _employeeID;
	private String _skill;
	private String _version;
	private boolean _certification;

	public <T> T getColumnValue(String columnName) {
		Function<skills, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((skills)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("skillId", _skillId);
		_columnOriginalValues.put("employeeID", _employeeID);
		_columnOriginalValues.put("skill", _skill);
		_columnOriginalValues.put("version", _version);
		_columnOriginalValues.put("certification", _certification);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("skillId", 1L);

		columnBitmasks.put("employeeID", 2L);

		columnBitmasks.put("skill", 4L);

		columnBitmasks.put("version", 8L);

		columnBitmasks.put("certification", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private skills _escapedModel;

}