/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.intranet.model.impl;

import com.intranet.model.Specialization;
import com.intranet.model.SpecializationModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Specialization service. Represents a row in the &quot;INTRANET_Specialization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SpecializationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SpecializationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SpecializationImpl
 * @generated
 */
public class SpecializationModelImpl
	extends BaseModelImpl<Specialization> implements SpecializationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a specialization model instance should use the <code>Specialization</code> interface instead.
	 */
	public static final String TABLE_NAME = "INTRANET_Specialization";

	public static final Object[][] TABLE_COLUMNS = {
		{"graduationCode", Types.VARCHAR},
		{"specializationName", Types.VARCHAR}, {"spCode", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("graduationCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("specializationName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("spCode", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table INTRANET_Specialization (graduationCode VARCHAR(75) null,specializationName VARCHAR(75) null,spCode LONG not null primary key)";

	public static final String TABLE_SQL_DROP =
		"drop table INTRANET_Specialization";

	public static final String ORDER_BY_JPQL =
		" ORDER BY specialization.spCode ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY INTRANET_Specialization.spCode ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GRADUATIONCODE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SPCODE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public SpecializationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _spCode;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSpCode(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _spCode;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Specialization.class;
	}

	@Override
	public String getModelClassName() {
		return Specialization.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Specialization, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Specialization, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Specialization, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Specialization)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Specialization, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Specialization, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Specialization)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Specialization, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Specialization, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Specialization, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Specialization, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Specialization, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Specialization, Object>>();
		Map<String, BiConsumer<Specialization, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Specialization, ?>>();

		attributeGetterFunctions.put(
			"graduationCode", Specialization::getGraduationCode);
		attributeSetterBiConsumers.put(
			"graduationCode",
			(BiConsumer<Specialization, String>)
				Specialization::setGraduationCode);
		attributeGetterFunctions.put(
			"specializationName", Specialization::getSpecializationName);
		attributeSetterBiConsumers.put(
			"specializationName",
			(BiConsumer<Specialization, String>)
				Specialization::setSpecializationName);
		attributeGetterFunctions.put("spCode", Specialization::getSpCode);
		attributeSetterBiConsumers.put(
			"spCode",
			(BiConsumer<Specialization, Long>)Specialization::setSpCode);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getGraduationCode() {
		if (_graduationCode == null) {
			return "";
		}
		else {
			return _graduationCode;
		}
	}

	@Override
	public void setGraduationCode(String graduationCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_graduationCode = graduationCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalGraduationCode() {
		return getColumnOriginalValue("graduationCode");
	}

	@Override
	public String getSpecializationName() {
		if (_specializationName == null) {
			return "";
		}
		else {
			return _specializationName;
		}
	}

	@Override
	public void setSpecializationName(String specializationName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_specializationName = specializationName;
	}

	@Override
	public long getSpCode() {
		return _spCode;
	}

	@Override
	public void setSpCode(long spCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_spCode = spCode;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Specialization.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Specialization toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Specialization>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SpecializationImpl specializationImpl = new SpecializationImpl();

		specializationImpl.setGraduationCode(getGraduationCode());
		specializationImpl.setSpecializationName(getSpecializationName());
		specializationImpl.setSpCode(getSpCode());

		specializationImpl.resetOriginalValues();

		return specializationImpl;
	}

	@Override
	public Specialization cloneWithOriginalValues() {
		SpecializationImpl specializationImpl = new SpecializationImpl();

		specializationImpl.setGraduationCode(
			this.<String>getColumnOriginalValue("graduationCode"));
		specializationImpl.setSpecializationName(
			this.<String>getColumnOriginalValue("specializationName"));
		specializationImpl.setSpCode(
			this.<Long>getColumnOriginalValue("spCode"));

		return specializationImpl;
	}

	@Override
	public int compareTo(Specialization specialization) {
		long primaryKey = specialization.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Specialization)) {
			return false;
		}

		Specialization specialization = (Specialization)object;

		long primaryKey = specialization.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Specialization> toCacheModel() {
		SpecializationCacheModel specializationCacheModel =
			new SpecializationCacheModel();

		specializationCacheModel.graduationCode = getGraduationCode();

		String graduationCode = specializationCacheModel.graduationCode;

		if ((graduationCode != null) && (graduationCode.length() == 0)) {
			specializationCacheModel.graduationCode = null;
		}

		specializationCacheModel.specializationName = getSpecializationName();

		String specializationName = specializationCacheModel.specializationName;

		if ((specializationName != null) &&
			(specializationName.length() == 0)) {

			specializationCacheModel.specializationName = null;
		}

		specializationCacheModel.spCode = getSpCode();

		return specializationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Specialization, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Specialization, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Specialization, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Specialization)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Specialization, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Specialization, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Specialization, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Specialization)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Specialization>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Specialization.class, ModelWrapper.class);

	}

	private String _graduationCode;
	private String _specializationName;
	private long _spCode;

	public <T> T getColumnValue(String columnName) {
		Function<Specialization, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Specialization)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("graduationCode", _graduationCode);
		_columnOriginalValues.put("specializationName", _specializationName);
		_columnOriginalValues.put("spCode", _spCode);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("graduationCode", 1L);

		columnBitmasks.put("specializationName", 2L);

		columnBitmasks.put("spCode", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Specialization _escapedModel;

}