/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package Example.service.base;

import Example.model.FirstTable;

import Example.service.FirstTableLocalService;
import Example.service.FirstTableLocalServiceUtil;
import Example.service.persistence.FirstTablePersistence;
import Example.service.persistence.SecondTablePersistence;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the first table local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link Example.service.impl.FirstTableLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Example.service.impl.FirstTableLocalServiceImpl
 * @generated
 */
public abstract class FirstTableLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, FirstTableLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>FirstTableLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>FirstTableLocalServiceUtil</code>.
	 */

	/**
	 * Adds the first table to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FirstTableLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param firstTable the first table
	 * @return the first table that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public FirstTable addFirstTable(FirstTable firstTable) {
		firstTable.setNew(true);

		return firstTablePersistence.update(firstTable);
	}

	/**
	 * Creates a new first table with the primary key. Does not add the first table to the database.
	 *
	 * @param soId the primary key for the new first table
	 * @return the new first table
	 */
	@Override
	@Transactional(enabled = false)
	public FirstTable createFirstTable(long soId) {
		return firstTablePersistence.create(soId);
	}

	/**
	 * Deletes the first table with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FirstTableLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param soId the primary key of the first table
	 * @return the first table that was removed
	 * @throws PortalException if a first table with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public FirstTable deleteFirstTable(long soId) throws PortalException {
		return firstTablePersistence.remove(soId);
	}

	/**
	 * Deletes the first table from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FirstTableLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param firstTable the first table
	 * @return the first table that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public FirstTable deleteFirstTable(FirstTable firstTable) {
		return firstTablePersistence.remove(firstTable);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return firstTablePersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			FirstTable.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return firstTablePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>Example.model.impl.FirstTableModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return firstTablePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>Example.model.impl.FirstTableModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return firstTablePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return firstTablePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return firstTablePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public FirstTable fetchFirstTable(long soId) {
		return firstTablePersistence.fetchByPrimaryKey(soId);
	}

	/**
	 * Returns the first table with the primary key.
	 *
	 * @param soId the primary key of the first table
	 * @return the first table
	 * @throws PortalException if a first table with the primary key could not be found
	 */
	@Override
	public FirstTable getFirstTable(long soId) throws PortalException {
		return firstTablePersistence.findByPrimaryKey(soId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(firstTableLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(FirstTable.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("soId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			firstTableLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(FirstTable.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("soId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(firstTableLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(FirstTable.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("soId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return firstTablePersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement FirstTableLocalServiceImpl#deleteFirstTable(FirstTable) to avoid orphaned data");
		}

		return firstTableLocalService.deleteFirstTable(
			(FirstTable)persistedModel);
	}

	@Override
	public BasePersistence<FirstTable> getBasePersistence() {
		return firstTablePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return firstTablePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the first tables.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>Example.model.impl.FirstTableModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of first tables
	 * @param end the upper bound of the range of first tables (not inclusive)
	 * @return the range of first tables
	 */
	@Override
	public List<FirstTable> getFirstTables(int start, int end) {
		return firstTablePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of first tables.
	 *
	 * @return the number of first tables
	 */
	@Override
	public int getFirstTablesCount() {
		return firstTablePersistence.countAll();
	}

	/**
	 * Updates the first table in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FirstTableLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param firstTable the first table
	 * @return the first table that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public FirstTable updateFirstTable(FirstTable firstTable) {
		return firstTablePersistence.update(firstTable);
	}

	/**
	 */
	@Override
	public void addSecondTableFirstTable(long coId, long soId) {
		secondTablePersistence.addFirstTable(coId, soId);
	}

	/**
	 */
	@Override
	public void addSecondTableFirstTable(long coId, FirstTable firstTable) {
		secondTablePersistence.addFirstTable(coId, firstTable);
	}

	/**
	 */
	@Override
	public void addSecondTableFirstTables(long coId, long[] soIds) {
		secondTablePersistence.addFirstTables(coId, soIds);
	}

	/**
	 */
	@Override
	public void addSecondTableFirstTables(
		long coId, List<FirstTable> firstTables) {

		secondTablePersistence.addFirstTables(coId, firstTables);
	}

	/**
	 */
	@Override
	public void clearSecondTableFirstTables(long coId) {
		secondTablePersistence.clearFirstTables(coId);
	}

	/**
	 */
	@Override
	public void deleteSecondTableFirstTable(long coId, long soId) {
		secondTablePersistence.removeFirstTable(coId, soId);
	}

	/**
	 */
	@Override
	public void deleteSecondTableFirstTable(long coId, FirstTable firstTable) {
		secondTablePersistence.removeFirstTable(coId, firstTable);
	}

	/**
	 */
	@Override
	public void deleteSecondTableFirstTables(long coId, long[] soIds) {
		secondTablePersistence.removeFirstTables(coId, soIds);
	}

	/**
	 */
	@Override
	public void deleteSecondTableFirstTables(
		long coId, List<FirstTable> firstTables) {

		secondTablePersistence.removeFirstTables(coId, firstTables);
	}

	/**
	 * Returns the coIds of the second tables associated with the first table.
	 *
	 * @param soId the soId of the first table
	 * @return long[] the coIds of second tables associated with the first table
	 */
	@Override
	public long[] getSecondTablePrimaryKeys(long soId) {
		return firstTablePersistence.getSecondTablePrimaryKeys(soId);
	}

	/**
	 */
	@Override
	public List<FirstTable> getSecondTableFirstTables(long coId) {
		return firstTablePersistence.getSecondTableFirstTables(coId);
	}

	/**
	 */
	@Override
	public List<FirstTable> getSecondTableFirstTables(
		long coId, int start, int end) {

		return firstTablePersistence.getSecondTableFirstTables(
			coId, start, end);
	}

	/**
	 */
	@Override
	public List<FirstTable> getSecondTableFirstTables(
		long coId, int start, int end,
		OrderByComparator<FirstTable> orderByComparator) {

		return firstTablePersistence.getSecondTableFirstTables(
			coId, start, end, orderByComparator);
	}

	/**
	 */
	@Override
	public int getSecondTableFirstTablesCount(long coId) {
		return secondTablePersistence.getFirstTablesSize(coId);
	}

	/**
	 */
	@Override
	public boolean hasSecondTableFirstTable(long coId, long soId) {
		return secondTablePersistence.containsFirstTable(coId, soId);
	}

	/**
	 */
	@Override
	public boolean hasSecondTableFirstTables(long coId) {
		return secondTablePersistence.containsFirstTables(coId);
	}

	/**
	 */
	@Override
	public void setSecondTableFirstTables(long coId, long[] soIds) {
		secondTablePersistence.setFirstTables(coId, soIds);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			FirstTableLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		firstTableLocalService = (FirstTableLocalService)aopProxy;

		_setLocalServiceUtilService(firstTableLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return FirstTableLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return FirstTable.class;
	}

	protected String getModelClassName() {
		return FirstTable.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = firstTablePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		FirstTableLocalService firstTableLocalService) {

		try {
			Field field = FirstTableLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, firstTableLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	protected FirstTableLocalService firstTableLocalService;

	@Reference
	protected FirstTablePersistence firstTablePersistence;

	@Reference
	protected SecondTablePersistence secondTablePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		FirstTableLocalServiceBaseImpl.class);

}