/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package Example.service.base;

import Example.model.SecondTable;

import Example.service.SecondTableLocalService;
import Example.service.SecondTableLocalServiceUtil;
import Example.service.persistence.FirstTablePersistence;
import Example.service.persistence.SecondTablePersistence;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the second table local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link Example.service.impl.SecondTableLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Example.service.impl.SecondTableLocalServiceImpl
 * @generated
 */
public abstract class SecondTableLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, SecondTableLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>SecondTableLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>SecondTableLocalServiceUtil</code>.
	 */

	/**
	 * Adds the second table to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect SecondTableLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param secondTable the second table
	 * @return the second table that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public SecondTable addSecondTable(SecondTable secondTable) {
		secondTable.setNew(true);

		return secondTablePersistence.update(secondTable);
	}

	/**
	 * Creates a new second table with the primary key. Does not add the second table to the database.
	 *
	 * @param coId the primary key for the new second table
	 * @return the new second table
	 */
	@Override
	@Transactional(enabled = false)
	public SecondTable createSecondTable(long coId) {
		return secondTablePersistence.create(coId);
	}

	/**
	 * Deletes the second table with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect SecondTableLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param coId the primary key of the second table
	 * @return the second table that was removed
	 * @throws PortalException if a second table with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public SecondTable deleteSecondTable(long coId) throws PortalException {
		return secondTablePersistence.remove(coId);
	}

	/**
	 * Deletes the second table from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect SecondTableLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param secondTable the second table
	 * @return the second table that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public SecondTable deleteSecondTable(SecondTable secondTable) {
		return secondTablePersistence.remove(secondTable);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return secondTablePersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			SecondTable.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return secondTablePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>Example.model.impl.SecondTableModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return secondTablePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>Example.model.impl.SecondTableModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return secondTablePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return secondTablePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return secondTablePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public SecondTable fetchSecondTable(long coId) {
		return secondTablePersistence.fetchByPrimaryKey(coId);
	}

	/**
	 * Returns the second table with the primary key.
	 *
	 * @param coId the primary key of the second table
	 * @return the second table
	 * @throws PortalException if a second table with the primary key could not be found
	 */
	@Override
	public SecondTable getSecondTable(long coId) throws PortalException {
		return secondTablePersistence.findByPrimaryKey(coId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(secondTableLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(SecondTable.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("coId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			secondTableLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(SecondTable.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("coId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(secondTableLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(SecondTable.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("coId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return secondTablePersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement SecondTableLocalServiceImpl#deleteSecondTable(SecondTable) to avoid orphaned data");
		}

		return secondTableLocalService.deleteSecondTable(
			(SecondTable)persistedModel);
	}

	@Override
	public BasePersistence<SecondTable> getBasePersistence() {
		return secondTablePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return secondTablePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the second tables.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>Example.model.impl.SecondTableModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of second tables
	 * @param end the upper bound of the range of second tables (not inclusive)
	 * @return the range of second tables
	 */
	@Override
	public List<SecondTable> getSecondTables(int start, int end) {
		return secondTablePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of second tables.
	 *
	 * @return the number of second tables
	 */
	@Override
	public int getSecondTablesCount() {
		return secondTablePersistence.countAll();
	}

	/**
	 * Updates the second table in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect SecondTableLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param secondTable the second table
	 * @return the second table that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public SecondTable updateSecondTable(SecondTable secondTable) {
		return secondTablePersistence.update(secondTable);
	}

	/**
	 */
	@Override
	public void addFirstTableSecondTable(long soId, long coId) {
		firstTablePersistence.addSecondTable(soId, coId);
	}

	/**
	 */
	@Override
	public void addFirstTableSecondTable(long soId, SecondTable secondTable) {
		firstTablePersistence.addSecondTable(soId, secondTable);
	}

	/**
	 */
	@Override
	public void addFirstTableSecondTables(long soId, long[] coIds) {
		firstTablePersistence.addSecondTables(soId, coIds);
	}

	/**
	 */
	@Override
	public void addFirstTableSecondTables(
		long soId, List<SecondTable> secondTables) {

		firstTablePersistence.addSecondTables(soId, secondTables);
	}

	/**
	 */
	@Override
	public void clearFirstTableSecondTables(long soId) {
		firstTablePersistence.clearSecondTables(soId);
	}

	/**
	 */
	@Override
	public void deleteFirstTableSecondTable(long soId, long coId) {
		firstTablePersistence.removeSecondTable(soId, coId);
	}

	/**
	 */
	@Override
	public void deleteFirstTableSecondTable(
		long soId, SecondTable secondTable) {

		firstTablePersistence.removeSecondTable(soId, secondTable);
	}

	/**
	 */
	@Override
	public void deleteFirstTableSecondTables(long soId, long[] coIds) {
		firstTablePersistence.removeSecondTables(soId, coIds);
	}

	/**
	 */
	@Override
	public void deleteFirstTableSecondTables(
		long soId, List<SecondTable> secondTables) {

		firstTablePersistence.removeSecondTables(soId, secondTables);
	}

	/**
	 * Returns the soIds of the first tables associated with the second table.
	 *
	 * @param coId the coId of the second table
	 * @return long[] the soIds of first tables associated with the second table
	 */
	@Override
	public long[] getFirstTablePrimaryKeys(long coId) {
		return secondTablePersistence.getFirstTablePrimaryKeys(coId);
	}

	/**
	 */
	@Override
	public List<SecondTable> getFirstTableSecondTables(long soId) {
		return secondTablePersistence.getFirstTableSecondTables(soId);
	}

	/**
	 */
	@Override
	public List<SecondTable> getFirstTableSecondTables(
		long soId, int start, int end) {

		return secondTablePersistence.getFirstTableSecondTables(
			soId, start, end);
	}

	/**
	 */
	@Override
	public List<SecondTable> getFirstTableSecondTables(
		long soId, int start, int end,
		OrderByComparator<SecondTable> orderByComparator) {

		return secondTablePersistence.getFirstTableSecondTables(
			soId, start, end, orderByComparator);
	}

	/**
	 */
	@Override
	public int getFirstTableSecondTablesCount(long soId) {
		return firstTablePersistence.getSecondTablesSize(soId);
	}

	/**
	 */
	@Override
	public boolean hasFirstTableSecondTable(long soId, long coId) {
		return firstTablePersistence.containsSecondTable(soId, coId);
	}

	/**
	 */
	@Override
	public boolean hasFirstTableSecondTables(long soId) {
		return firstTablePersistence.containsSecondTables(soId);
	}

	/**
	 */
	@Override
	public void setFirstTableSecondTables(long soId, long[] coIds) {
		firstTablePersistence.setSecondTables(soId, coIds);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			SecondTableLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		secondTableLocalService = (SecondTableLocalService)aopProxy;

		_setLocalServiceUtilService(secondTableLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return SecondTableLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return SecondTable.class;
	}

	protected String getModelClassName() {
		return SecondTable.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = secondTablePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		SecondTableLocalService secondTableLocalService) {

		try {
			Field field = SecondTableLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, secondTableLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected FirstTablePersistence firstTablePersistence;

	protected SecondTableLocalService secondTableLocalService;

	@Reference
	protected SecondTablePersistence secondTablePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		SecondTableLocalServiceBaseImpl.class);

}