/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package api.master.slayer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MasterUrl service. Represents a row in the &quot;API_MasterUrl&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>api.master.slayer.model.impl.MasterUrlModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>api.master.slayer.model.impl.MasterUrlImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MasterUrl
 * @generated
 */
@ProviderType
public interface MasterUrlModel
	extends BaseModel<MasterUrl>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a master url model instance should use the {@link MasterUrl} interface instead.
	 */

	/**
	 * Returns the primary key of this master url.
	 *
	 * @return the primary key of this master url
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this master url.
	 *
	 * @param primaryKey the primary key of this master url
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this master url.
	 *
	 * @return the uuid of this master url
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this master url.
	 *
	 * @param uuid the uuid of this master url
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the master url ID of this master url.
	 *
	 * @return the master url ID of this master url
	 */
	public long getMasterUrlId();

	/**
	 * Sets the master url ID of this master url.
	 *
	 * @param masterUrlId the master url ID of this master url
	 */
	public void setMasterUrlId(long masterUrlId);

	/**
	 * Returns the app name of this master url.
	 *
	 * @return the app name of this master url
	 */
	@AutoEscape
	public String getAppName();

	/**
	 * Sets the app name of this master url.
	 *
	 * @param appName the app name of this master url
	 */
	public void setAppName(String appName);

	/**
	 * Returns the base url of this master url.
	 *
	 * @return the base url of this master url
	 */
	@AutoEscape
	public String getBaseUrl();

	/**
	 * Sets the base url of this master url.
	 *
	 * @param baseUrl the base url of this master url
	 */
	public void setBaseUrl(String baseUrl);

	/**
	 * Returns the svg icon of this master url.
	 *
	 * @return the svg icon of this master url
	 */
	@AutoEscape
	public String getSvgIcon();

	/**
	 * Sets the svg icon of this master url.
	 *
	 * @param svgIcon the svg icon of this master url
	 */
	public void setSvgIcon(String svgIcon);

	/**
	 * Returns the user ID of this master url.
	 *
	 * @return the user ID of this master url
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this master url.
	 *
	 * @param userId the user ID of this master url
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this master url.
	 *
	 * @return the user uuid of this master url
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this master url.
	 *
	 * @param userUuid the user uuid of this master url
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this master url.
	 *
	 * @return the group ID of this master url
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this master url.
	 *
	 * @param groupId the group ID of this master url
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this master url.
	 *
	 * @return the company ID of this master url
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this master url.
	 *
	 * @param companyId the company ID of this master url
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this master url.
	 *
	 * @return the create date of this master url
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this master url.
	 *
	 * @param createDate the create date of this master url
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this master url.
	 *
	 * @return the modified date of this master url
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this master url.
	 *
	 * @param modifiedDate the modified date of this master url
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public MasterUrl cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}