/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.student.info.service.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.student.info.service.model.Parent;
import com.student.info.service.service.ParentLocalService;
import com.student.info.service.service.ParentLocalServiceUtil;
import com.student.info.service.service.persistence.CoursePersistence;
import com.student.info.service.service.persistence.ParentPersistence;
import com.student.info.service.service.persistence.StudentPersistence;
import com.student.info.service.service.persistence.TeacherPersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the parent local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.student.info.service.service.impl.ParentLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.student.info.service.service.impl.ParentLocalServiceImpl
 * @generated
 */
public abstract class ParentLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, ParentLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ParentLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>ParentLocalServiceUtil</code>.
	 */

	/**
	 * Adds the parent to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ParentLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param parent the parent
	 * @return the parent that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Parent addParent(Parent parent) {
		parent.setNew(true);

		return parentPersistence.update(parent);
	}

	/**
	 * Creates a new parent with the primary key. Does not add the parent to the database.
	 *
	 * @param parentId the primary key for the new parent
	 * @return the new parent
	 */
	@Override
	@Transactional(enabled = false)
	public Parent createParent(long parentId) {
		return parentPersistence.create(parentId);
	}

	/**
	 * Deletes the parent with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ParentLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param parentId the primary key of the parent
	 * @return the parent that was removed
	 * @throws PortalException if a parent with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Parent deleteParent(long parentId) throws PortalException {
		return parentPersistence.remove(parentId);
	}

	/**
	 * Deletes the parent from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ParentLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param parent the parent
	 * @return the parent that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Parent deleteParent(Parent parent) {
		return parentPersistence.remove(parent);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return parentPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			Parent.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return parentPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.student.info.service.model.impl.ParentModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return parentPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.student.info.service.model.impl.ParentModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return parentPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return parentPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return parentPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public Parent fetchParent(long parentId) {
		return parentPersistence.fetchByPrimaryKey(parentId);
	}

	/**
	 * Returns the parent with the primary key.
	 *
	 * @param parentId the primary key of the parent
	 * @return the parent
	 * @throws PortalException if a parent with the primary key could not be found
	 */
	@Override
	public Parent getParent(long parentId) throws PortalException {
		return parentPersistence.findByPrimaryKey(parentId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(parentLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Parent.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("parentId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(parentLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(Parent.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("parentId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(parentLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Parent.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("parentId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return parentPersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement ParentLocalServiceImpl#deleteParent(Parent) to avoid orphaned data");
		}

		return parentLocalService.deleteParent((Parent)persistedModel);
	}

	@Override
	public BasePersistence<Parent> getBasePersistence() {
		return parentPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return parentPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the parents.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.student.info.service.model.impl.ParentModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of parents
	 * @param end the upper bound of the range of parents (not inclusive)
	 * @return the range of parents
	 */
	@Override
	public List<Parent> getParents(int start, int end) {
		return parentPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of parents.
	 *
	 * @return the number of parents
	 */
	@Override
	public int getParentsCount() {
		return parentPersistence.countAll();
	}

	/**
	 * Updates the parent in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ParentLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param parent the parent
	 * @return the parent that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Parent updateParent(Parent parent) {
		return parentPersistence.update(parent);
	}

	/**
	 */
	@Override
	public void addStudentParent(long studentId, long parentId) {
		studentPersistence.addParent(studentId, parentId);
	}

	/**
	 */
	@Override
	public void addStudentParent(long studentId, Parent parent) {
		studentPersistence.addParent(studentId, parent);
	}

	/**
	 */
	@Override
	public void addStudentParents(long studentId, long[] parentIds) {
		studentPersistence.addParents(studentId, parentIds);
	}

	/**
	 */
	@Override
	public void addStudentParents(long studentId, List<Parent> parents) {
		studentPersistence.addParents(studentId, parents);
	}

	/**
	 */
	@Override
	public void clearStudentParents(long studentId) {
		studentPersistence.clearParents(studentId);
	}

	/**
	 */
	@Override
	public void deleteStudentParent(long studentId, long parentId) {
		studentPersistence.removeParent(studentId, parentId);
	}

	/**
	 */
	@Override
	public void deleteStudentParent(long studentId, Parent parent) {
		studentPersistence.removeParent(studentId, parent);
	}

	/**
	 */
	@Override
	public void deleteStudentParents(long studentId, long[] parentIds) {
		studentPersistence.removeParents(studentId, parentIds);
	}

	/**
	 */
	@Override
	public void deleteStudentParents(long studentId, List<Parent> parents) {
		studentPersistence.removeParents(studentId, parents);
	}

	/**
	 * Returns the studentIds of the students associated with the parent.
	 *
	 * @param parentId the parentId of the parent
	 * @return long[] the studentIds of students associated with the parent
	 */
	@Override
	public long[] getStudentPrimaryKeys(long parentId) {
		return parentPersistence.getStudentPrimaryKeys(parentId);
	}

	/**
	 */
	@Override
	public List<Parent> getStudentParents(long studentId) {
		return parentPersistence.getStudentParents(studentId);
	}

	/**
	 */
	@Override
	public List<Parent> getStudentParents(long studentId, int start, int end) {
		return parentPersistence.getStudentParents(studentId, start, end);
	}

	/**
	 */
	@Override
	public List<Parent> getStudentParents(
		long studentId, int start, int end,
		OrderByComparator<Parent> orderByComparator) {

		return parentPersistence.getStudentParents(
			studentId, start, end, orderByComparator);
	}

	/**
	 */
	@Override
	public int getStudentParentsCount(long studentId) {
		return studentPersistence.getParentsSize(studentId);
	}

	/**
	 */
	@Override
	public boolean hasStudentParent(long studentId, long parentId) {
		return studentPersistence.containsParent(studentId, parentId);
	}

	/**
	 */
	@Override
	public boolean hasStudentParents(long studentId) {
		return studentPersistence.containsParents(studentId);
	}

	/**
	 */
	@Override
	public void setStudentParents(long studentId, long[] parentIds) {
		studentPersistence.setParents(studentId, parentIds);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			ParentLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		parentLocalService = (ParentLocalService)aopProxy;

		_setLocalServiceUtilService(parentLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ParentLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Parent.class;
	}

	protected String getModelClassName() {
		return Parent.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = parentPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		ParentLocalService parentLocalService) {

		try {
			Field field = ParentLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, parentLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected CoursePersistence coursePersistence;

	protected ParentLocalService parentLocalService;

	@Reference
	protected ParentPersistence parentPersistence;

	@Reference
	protected StudentPersistence studentPersistence;

	@Reference
	protected TeacherPersistence teacherPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		ParentLocalServiceBaseImpl.class);

}