/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.student.info.service.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.student.info.service.model.Teacher;
import com.student.info.service.service.TeacherLocalService;
import com.student.info.service.service.TeacherLocalServiceUtil;
import com.student.info.service.service.persistence.CoursePersistence;
import com.student.info.service.service.persistence.ParentPersistence;
import com.student.info.service.service.persistence.StudentPersistence;
import com.student.info.service.service.persistence.TeacherPersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the teacher local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.student.info.service.service.impl.TeacherLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.student.info.service.service.impl.TeacherLocalServiceImpl
 * @generated
 */
public abstract class TeacherLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, TeacherLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>TeacherLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>TeacherLocalServiceUtil</code>.
	 */

	/**
	 * Adds the teacher to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect TeacherLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param teacher the teacher
	 * @return the teacher that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Teacher addTeacher(Teacher teacher) {
		teacher.setNew(true);

		return teacherPersistence.update(teacher);
	}

	/**
	 * Creates a new teacher with the primary key. Does not add the teacher to the database.
	 *
	 * @param teacherId the primary key for the new teacher
	 * @return the new teacher
	 */
	@Override
	@Transactional(enabled = false)
	public Teacher createTeacher(long teacherId) {
		return teacherPersistence.create(teacherId);
	}

	/**
	 * Deletes the teacher with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect TeacherLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param teacherId the primary key of the teacher
	 * @return the teacher that was removed
	 * @throws PortalException if a teacher with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Teacher deleteTeacher(long teacherId) throws PortalException {
		return teacherPersistence.remove(teacherId);
	}

	/**
	 * Deletes the teacher from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect TeacherLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param teacher the teacher
	 * @return the teacher that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Teacher deleteTeacher(Teacher teacher) {
		return teacherPersistence.remove(teacher);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return teacherPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			Teacher.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return teacherPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.student.info.service.model.impl.TeacherModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return teacherPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.student.info.service.model.impl.TeacherModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return teacherPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return teacherPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return teacherPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public Teacher fetchTeacher(long teacherId) {
		return teacherPersistence.fetchByPrimaryKey(teacherId);
	}

	/**
	 * Returns the teacher with the primary key.
	 *
	 * @param teacherId the primary key of the teacher
	 * @return the teacher
	 * @throws PortalException if a teacher with the primary key could not be found
	 */
	@Override
	public Teacher getTeacher(long teacherId) throws PortalException {
		return teacherPersistence.findByPrimaryKey(teacherId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(teacherLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Teacher.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("teacherId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			teacherLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(Teacher.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("teacherId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(teacherLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Teacher.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("teacherId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return teacherPersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement TeacherLocalServiceImpl#deleteTeacher(Teacher) to avoid orphaned data");
		}

		return teacherLocalService.deleteTeacher((Teacher)persistedModel);
	}

	@Override
	public BasePersistence<Teacher> getBasePersistence() {
		return teacherPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return teacherPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the teachers.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.student.info.service.model.impl.TeacherModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of teachers
	 * @param end the upper bound of the range of teachers (not inclusive)
	 * @return the range of teachers
	 */
	@Override
	public List<Teacher> getTeachers(int start, int end) {
		return teacherPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of teachers.
	 *
	 * @return the number of teachers
	 */
	@Override
	public int getTeachersCount() {
		return teacherPersistence.countAll();
	}

	/**
	 * Updates the teacher in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect TeacherLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param teacher the teacher
	 * @return the teacher that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Teacher updateTeacher(Teacher teacher) {
		return teacherPersistence.update(teacher);
	}

	/**
	 */
	@Override
	public void addStudentTeacher(long studentId, long teacherId) {
		studentPersistence.addTeacher(studentId, teacherId);
	}

	/**
	 */
	@Override
	public void addStudentTeacher(long studentId, Teacher teacher) {
		studentPersistence.addTeacher(studentId, teacher);
	}

	/**
	 */
	@Override
	public void addStudentTeachers(long studentId, long[] teacherIds) {
		studentPersistence.addTeachers(studentId, teacherIds);
	}

	/**
	 */
	@Override
	public void addStudentTeachers(long studentId, List<Teacher> teachers) {
		studentPersistence.addTeachers(studentId, teachers);
	}

	/**
	 */
	@Override
	public void clearStudentTeachers(long studentId) {
		studentPersistence.clearTeachers(studentId);
	}

	/**
	 */
	@Override
	public void deleteStudentTeacher(long studentId, long teacherId) {
		studentPersistence.removeTeacher(studentId, teacherId);
	}

	/**
	 */
	@Override
	public void deleteStudentTeacher(long studentId, Teacher teacher) {
		studentPersistence.removeTeacher(studentId, teacher);
	}

	/**
	 */
	@Override
	public void deleteStudentTeachers(long studentId, long[] teacherIds) {
		studentPersistence.removeTeachers(studentId, teacherIds);
	}

	/**
	 */
	@Override
	public void deleteStudentTeachers(long studentId, List<Teacher> teachers) {
		studentPersistence.removeTeachers(studentId, teachers);
	}

	/**
	 * Returns the studentIds of the students associated with the teacher.
	 *
	 * @param teacherId the teacherId of the teacher
	 * @return long[] the studentIds of students associated with the teacher
	 */
	@Override
	public long[] getStudentPrimaryKeys(long teacherId) {
		return teacherPersistence.getStudentPrimaryKeys(teacherId);
	}

	/**
	 */
	@Override
	public List<Teacher> getStudentTeachers(long studentId) {
		return teacherPersistence.getStudentTeachers(studentId);
	}

	/**
	 */
	@Override
	public List<Teacher> getStudentTeachers(
		long studentId, int start, int end) {

		return teacherPersistence.getStudentTeachers(studentId, start, end);
	}

	/**
	 */
	@Override
	public List<Teacher> getStudentTeachers(
		long studentId, int start, int end,
		OrderByComparator<Teacher> orderByComparator) {

		return teacherPersistence.getStudentTeachers(
			studentId, start, end, orderByComparator);
	}

	/**
	 */
	@Override
	public int getStudentTeachersCount(long studentId) {
		return studentPersistence.getTeachersSize(studentId);
	}

	/**
	 */
	@Override
	public boolean hasStudentTeacher(long studentId, long teacherId) {
		return studentPersistence.containsTeacher(studentId, teacherId);
	}

	/**
	 */
	@Override
	public boolean hasStudentTeachers(long studentId) {
		return studentPersistence.containsTeachers(studentId);
	}

	/**
	 */
	@Override
	public void setStudentTeachers(long studentId, long[] teacherIds) {
		studentPersistence.setTeachers(studentId, teacherIds);
	}

	/**
	 */
	@Override
	public void addCourseTeacher(long courseId, long teacherId) {
		coursePersistence.addTeacher(courseId, teacherId);
	}

	/**
	 */
	@Override
	public void addCourseTeacher(long courseId, Teacher teacher) {
		coursePersistence.addTeacher(courseId, teacher);
	}

	/**
	 */
	@Override
	public void addCourseTeachers(long courseId, long[] teacherIds) {
		coursePersistence.addTeachers(courseId, teacherIds);
	}

	/**
	 */
	@Override
	public void addCourseTeachers(long courseId, List<Teacher> teachers) {
		coursePersistence.addTeachers(courseId, teachers);
	}

	/**
	 */
	@Override
	public void clearCourseTeachers(long courseId) {
		coursePersistence.clearTeachers(courseId);
	}

	/**
	 */
	@Override
	public void deleteCourseTeacher(long courseId, long teacherId) {
		coursePersistence.removeTeacher(courseId, teacherId);
	}

	/**
	 */
	@Override
	public void deleteCourseTeacher(long courseId, Teacher teacher) {
		coursePersistence.removeTeacher(courseId, teacher);
	}

	/**
	 */
	@Override
	public void deleteCourseTeachers(long courseId, long[] teacherIds) {
		coursePersistence.removeTeachers(courseId, teacherIds);
	}

	/**
	 */
	@Override
	public void deleteCourseTeachers(long courseId, List<Teacher> teachers) {
		coursePersistence.removeTeachers(courseId, teachers);
	}

	/**
	 * Returns the courseIds of the courses associated with the teacher.
	 *
	 * @param teacherId the teacherId of the teacher
	 * @return long[] the courseIds of courses associated with the teacher
	 */
	@Override
	public long[] getCoursePrimaryKeys(long teacherId) {
		return teacherPersistence.getCoursePrimaryKeys(teacherId);
	}

	/**
	 */
	@Override
	public List<Teacher> getCourseTeachers(long courseId) {
		return teacherPersistence.getCourseTeachers(courseId);
	}

	/**
	 */
	@Override
	public List<Teacher> getCourseTeachers(long courseId, int start, int end) {
		return teacherPersistence.getCourseTeachers(courseId, start, end);
	}

	/**
	 */
	@Override
	public List<Teacher> getCourseTeachers(
		long courseId, int start, int end,
		OrderByComparator<Teacher> orderByComparator) {

		return teacherPersistence.getCourseTeachers(
			courseId, start, end, orderByComparator);
	}

	/**
	 */
	@Override
	public int getCourseTeachersCount(long courseId) {
		return coursePersistence.getTeachersSize(courseId);
	}

	/**
	 */
	@Override
	public boolean hasCourseTeacher(long courseId, long teacherId) {
		return coursePersistence.containsTeacher(courseId, teacherId);
	}

	/**
	 */
	@Override
	public boolean hasCourseTeachers(long courseId) {
		return coursePersistence.containsTeachers(courseId);
	}

	/**
	 */
	@Override
	public void setCourseTeachers(long courseId, long[] teacherIds) {
		coursePersistence.setTeachers(courseId, teacherIds);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			TeacherLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		teacherLocalService = (TeacherLocalService)aopProxy;

		_setLocalServiceUtilService(teacherLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return TeacherLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Teacher.class;
	}

	protected String getModelClassName() {
		return Teacher.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = teacherPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		TeacherLocalService teacherLocalService) {

		try {
			Field field = TeacherLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, teacherLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected CoursePersistence coursePersistence;

	@Reference
	protected ParentPersistence parentPersistence;

	@Reference
	protected StudentPersistence studentPersistence;

	protected TeacherLocalService teacherLocalService;

	@Reference
	protected TeacherPersistence teacherPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		TeacherLocalServiceBaseImpl.class);

}