/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package api.master.slayer.service.base;

import api.master.slayer.model.ApiMapKey;
import api.master.slayer.service.ApiMapKeyLocalService;
import api.master.slayer.service.ApiMapKeyLocalServiceUtil;
import api.master.slayer.service.persistence.ApiMapKeyPersistence;
import api.master.slayer.service.persistence.ConnectedAccountsPersistence;
import api.master.slayer.service.persistence.MasterMetaDataPersistence;
import api.master.slayer.service.persistence.MasterUrlPersistence;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the api map key local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link api.master.slayer.service.impl.ApiMapKeyLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see api.master.slayer.service.impl.ApiMapKeyLocalServiceImpl
 * @generated
 */
public abstract class ApiMapKeyLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, ApiMapKeyLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ApiMapKeyLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>ApiMapKeyLocalServiceUtil</code>.
	 */

	/**
	 * Adds the api map key to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ApiMapKeyLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param apiMapKey the api map key
	 * @return the api map key that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ApiMapKey addApiMapKey(ApiMapKey apiMapKey) {
		apiMapKey.setNew(true);

		return apiMapKeyPersistence.update(apiMapKey);
	}

	/**
	 * Creates a new api map key with the primary key. Does not add the api map key to the database.
	 *
	 * @param apiMapKeyId the primary key for the new api map key
	 * @return the new api map key
	 */
	@Override
	@Transactional(enabled = false)
	public ApiMapKey createApiMapKey(long apiMapKeyId) {
		return apiMapKeyPersistence.create(apiMapKeyId);
	}

	/**
	 * Deletes the api map key with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ApiMapKeyLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param apiMapKeyId the primary key of the api map key
	 * @return the api map key that was removed
	 * @throws PortalException if a api map key with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ApiMapKey deleteApiMapKey(long apiMapKeyId) throws PortalException {
		return apiMapKeyPersistence.remove(apiMapKeyId);
	}

	/**
	 * Deletes the api map key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ApiMapKeyLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param apiMapKey the api map key
	 * @return the api map key that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ApiMapKey deleteApiMapKey(ApiMapKey apiMapKey) {
		return apiMapKeyPersistence.remove(apiMapKey);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return apiMapKeyPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			ApiMapKey.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return apiMapKeyPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>api.master.slayer.model.impl.ApiMapKeyModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return apiMapKeyPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>api.master.slayer.model.impl.ApiMapKeyModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return apiMapKeyPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return apiMapKeyPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return apiMapKeyPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public ApiMapKey fetchApiMapKey(long apiMapKeyId) {
		return apiMapKeyPersistence.fetchByPrimaryKey(apiMapKeyId);
	}

	/**
	 * Returns the api map key matching the UUID and group.
	 *
	 * @param uuid the api map key's UUID
	 * @param groupId the primary key of the group
	 * @return the matching api map key, or <code>null</code> if a matching api map key could not be found
	 */
	@Override
	public ApiMapKey fetchApiMapKeyByUuidAndGroupId(String uuid, long groupId) {
		return apiMapKeyPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the api map key with the primary key.
	 *
	 * @param apiMapKeyId the primary key of the api map key
	 * @return the api map key
	 * @throws PortalException if a api map key with the primary key could not be found
	 */
	@Override
	public ApiMapKey getApiMapKey(long apiMapKeyId) throws PortalException {
		return apiMapKeyPersistence.findByPrimaryKey(apiMapKeyId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(apiMapKeyLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ApiMapKey.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("apiMapKeyId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			apiMapKeyLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(ApiMapKey.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"apiMapKeyId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(apiMapKeyLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ApiMapKey.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("apiMapKeyId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return apiMapKeyPersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement ApiMapKeyLocalServiceImpl#deleteApiMapKey(ApiMapKey) to avoid orphaned data");
		}

		return apiMapKeyLocalService.deleteApiMapKey((ApiMapKey)persistedModel);
	}

	@Override
	public BasePersistence<ApiMapKey> getBasePersistence() {
		return apiMapKeyPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return apiMapKeyPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns the api map key matching the UUID and group.
	 *
	 * @param uuid the api map key's UUID
	 * @param groupId the primary key of the group
	 * @return the matching api map key
	 * @throws PortalException if a matching api map key could not be found
	 */
	@Override
	public ApiMapKey getApiMapKeyByUuidAndGroupId(String uuid, long groupId)
		throws PortalException {

		return apiMapKeyPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the api map keys.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>api.master.slayer.model.impl.ApiMapKeyModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of api map keys
	 * @param end the upper bound of the range of api map keys (not inclusive)
	 * @return the range of api map keys
	 */
	@Override
	public List<ApiMapKey> getApiMapKeys(int start, int end) {
		return apiMapKeyPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of api map keys.
	 *
	 * @return the number of api map keys
	 */
	@Override
	public int getApiMapKeysCount() {
		return apiMapKeyPersistence.countAll();
	}

	/**
	 * Updates the api map key in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ApiMapKeyLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param apiMapKey the api map key
	 * @return the api map key that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ApiMapKey updateApiMapKey(ApiMapKey apiMapKey) {
		return apiMapKeyPersistence.update(apiMapKey);
	}

	@Deactivate
	protected void deactivate() {
		ApiMapKeyLocalServiceUtil.setService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			ApiMapKeyLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		apiMapKeyLocalService = (ApiMapKeyLocalService)aopProxy;

		ApiMapKeyLocalServiceUtil.setService(apiMapKeyLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ApiMapKeyLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ApiMapKey.class;
	}

	protected String getModelClassName() {
		return ApiMapKey.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = apiMapKeyPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected ApiMapKeyLocalService apiMapKeyLocalService;

	@Reference
	protected ApiMapKeyPersistence apiMapKeyPersistence;

	@Reference
	protected ConnectedAccountsPersistence connectedAccountsPersistence;

	@Reference
	protected MasterMetaDataPersistence masterMetaDataPersistence;

	@Reference
	protected MasterUrlPersistence masterUrlPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		ApiMapKeyLocalServiceBaseImpl.class);

}