/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package api.master.slayer.service.base;

import api.master.slayer.model.MasterMetaData;
import api.master.slayer.service.MasterMetaDataService;
import api.master.slayer.service.MasterMetaDataServiceUtil;
import api.master.slayer.service.persistence.ApiMapKeyPersistence;
import api.master.slayer.service.persistence.ConnectedAccountsPersistence;
import api.master.slayer.service.persistence.MasterMetaDataPersistence;
import api.master.slayer.service.persistence.MasterUrlPersistence;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the master meta data remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link api.master.slayer.service.impl.MasterMetaDataServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see api.master.slayer.service.impl.MasterMetaDataServiceImpl
 * @generated
 */
public abstract class MasterMetaDataServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, IdentifiableOSGiService, MasterMetaDataService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>MasterMetaDataService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>MasterMetaDataServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		MasterMetaDataServiceUtil.setService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			MasterMetaDataService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		masterMetaDataService = (MasterMetaDataService)aopProxy;

		MasterMetaDataServiceUtil.setService(masterMetaDataService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return MasterMetaDataService.class.getName();
	}

	protected Class<?> getModelClass() {
		return MasterMetaData.class;
	}

	protected String getModelClassName() {
		return MasterMetaData.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = masterMetaDataPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected ApiMapKeyPersistence apiMapKeyPersistence;

	@Reference
	protected ConnectedAccountsPersistence connectedAccountsPersistence;

	@Reference
	protected api.master.slayer.service.MasterMetaDataLocalService
		masterMetaDataLocalService;

	protected MasterMetaDataService masterMetaDataService;

	@Reference
	protected MasterMetaDataPersistence masterMetaDataPersistence;

	@Reference
	protected MasterUrlPersistence masterUrlPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		MasterMetaDataServiceBaseImpl.class);

}