components:
    schemas:
        Project:
            properties:
                actions:
                    additionalProperties:
                        additionalProperties:
                            type: string
                        type: object
                    readOnly: true
                    type: object
                name:
                    description: The client name.
                    type: string
                description:
                    type: string
                proposedDate:
                    format: date
                    type: string
                confirmedDate:
                    format: date
                    type: string
                developmentStartDate:
                    format: date
                    type: string
                durationDate:
                    type: string
                code:
                    type: integer
                id:
                    format: int64
                    type: integer
                projectName:
                    type: string
                status:
                    $ref: "#/components/schemas/Status"
                statusCode:
                    format: int32
                    type: integer
                projectManager:
                    type: string
                deliveryLead:
                    type: string
                operationLead:
                    type: string
                projectQaLead:
                    type: string
                contactNumber:
                    type: string
                contactEmail:
                    type: string
                pmId:
                    format: int64
                    type: integer
                dlId:
                    format: int64
                    type: integer
                olId:
                    format: int64
                    type: integer
                qlId:
                    format: int64
                    type: integer
            type: object
        Task:
            properties:
                actions:
                    additionalProperties:
                        additionalProperties:
                            type: string
                        type: object
                    readOnly: true
                    type: object
                name:
                    description: The client name.
                    type: string
                description:
                    type: string
                developmentTeamIds:
                    type: string
                developmentTeam:
                    type: string
                testerTeamIds:
                    type: string
                testerTeam:
                    type: string
                taskStartDate:
                    format: date
                    type: string
                taskEndDate:
                    format: date
                    type: string
                status:
                    $ref: "#/components/schemas/Status"
                id:
                    format: int64
                    type: integer
                projectId:
                    format: int64
                    type: integer
                projectCode:
                    format: int64
                    type: integer
            type: object
        Status:
            properties:
                code:
                    format: int32
                    type: integer
                label:
                    type: string
                label_i18n:
                    type: string
            type: object
info:
    description: "EsquareIntranetProjectHeadless REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "EsquareIntranetProjectHeadless"
    version: v1.0
openapi: 3.0.1
paths:
    "/projects-management":
        get:
            operationId: getProjectsManagementPage
            parameters:
                - in: query
                  name: filter
                  schema:
                      type: string
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
                - in: query
                  name: search
                  schema:
                      type: string
                - in: query
                  name: sort
                  schema:
                      type: string
            responses:
                200:
                    description: Getting Project Management response
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Project"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Project"
                                type: array
            tags: ["Project"]
    "/projects-management/{projectId}":
        delete:
            operationId: deleteProjectsManagementProject
            parameters:
                - in: path
                  name: projectId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                204:
                    description:
                        Successful delete Project
                    content:
                        application/json: { }
                        application/xml: { }
            tags: [ "Project" ]
        get:
            operationId: getProjectsManagementProject
            parameters:
                - in: path
                  name: projectId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    description:
                        Successful get Projects
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Project"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Project"
            tags: [ "Project" ]
    "/post-resources":
        patch:
            operationId: patchPostResource
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Project"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Project"
            responses:
                200:
                    description: Resources Added SuccessFully
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Project"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Project"
            tags: [ "Project" ]
    "/post-project-status":
        patch:
            operationId: patchPostProjectStatu
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Project"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Project"
            responses:
                200:
                    description: Project Status Updated
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Project"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Project"
            tags: [ "Project" ]
    "/get-task/{projectId}":
        get:
            operationId: getGetTasksProjectPage
            parameters:
                - in: path
                  name: projectId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    description: Getting Task response
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Task"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Task"
                                type: array
            tags: [ "Task" ]
    "/post-task":
        post:
            operationId: postPostTask
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Task"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Task"
            responses:
                200:
                    description: Task Added SuccessFully
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Task"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Task"
            tags: [ "Task" ]
    "/update-task":
        post:
            operationId: postUpdateTask
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Task"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Task"
            responses:
                200:
                    description: Task updated SuccessFully
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Task"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Task"
            tags: [ "Task" ]
