/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.prime.data.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the HighQualHeld service. Represents a row in the &quot;PRIME_HighQualHeld&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.prime.data.service.model.impl.HighQualHeldModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.prime.data.service.model.impl.HighQualHeldImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see HighQualHeld
 * @generated
 */
@ProviderType
public interface HighQualHeldModel extends BaseModel<HighQualHeld> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a high qual held model instance should use the {@link HighQualHeld} interface instead.
	 */

	/**
	 * Returns the primary key of this high qual held.
	 *
	 * @return the primary key of this high qual held
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this high qual held.
	 *
	 * @param primaryKey the primary key of this high qual held
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this high qual held.
	 *
	 * @return the uuid of this high qual held
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this high qual held.
	 *
	 * @param uuid the uuid of this high qual held
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the high qual held ID of this high qual held.
	 *
	 * @return the high qual held ID of this high qual held
	 */
	public long getHighQualHeldId();

	/**
	 * Sets the high qual held ID of this high qual held.
	 *
	 * @param highQualHeldId the high qual held ID of this high qual held
	 */
	public void setHighQualHeldId(long highQualHeldId);

	/**
	 * Returns the high qual held of this high qual held.
	 *
	 * @return the high qual held of this high qual held
	 */
	@AutoEscape
	public String getHighQualHeld();

	/**
	 * Sets the high qual held of this high qual held.
	 *
	 * @param highQualHeld the high qual held of this high qual held
	 */
	public void setHighQualHeld(String highQualHeld);

	@Override
	public HighQualHeld cloneWithOriginalValues();

}