/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.prime.data.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the InterviewName service. Represents a row in the &quot;PRIME_InterviewName&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.prime.data.service.model.impl.InterviewNameModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.prime.data.service.model.impl.InterviewNameImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see InterviewName
 * @generated
 */
@ProviderType
public interface InterviewNameModel extends BaseModel<InterviewName> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a interview name model instance should use the {@link InterviewName} interface instead.
	 */

	/**
	 * Returns the primary key of this interview name.
	 *
	 * @return the primary key of this interview name
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this interview name.
	 *
	 * @param primaryKey the primary key of this interview name
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this interview name.
	 *
	 * @return the uuid of this interview name
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this interview name.
	 *
	 * @param uuid the uuid of this interview name
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the interview name ID of this interview name.
	 *
	 * @return the interview name ID of this interview name
	 */
	public long getInterviewNameId();

	/**
	 * Sets the interview name ID of this interview name.
	 *
	 * @param interviewNameId the interview name ID of this interview name
	 */
	public void setInterviewNameId(long interviewNameId);

	/**
	 * Returns the interview name of this interview name.
	 *
	 * @return the interview name of this interview name
	 */
	@AutoEscape
	public String getInterviewName();

	/**
	 * Sets the interview name of this interview name.
	 *
	 * @param interviewName the interview name of this interview name
	 */
	public void setInterviewName(String interviewName);

	@Override
	public InterviewName cloneWithOriginalValues();

}