/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.prime.data.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the WorkExperience service. Represents a row in the &quot;PRIME_WorkExperience&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.prime.data.service.model.impl.WorkExperienceModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.prime.data.service.model.impl.WorkExperienceImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WorkExperience
 * @generated
 */
@ProviderType
public interface WorkExperienceModel extends BaseModel<WorkExperience> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a work experience model instance should use the {@link WorkExperience} interface instead.
	 */

	/**
	 * Returns the primary key of this work experience.
	 *
	 * @return the primary key of this work experience
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this work experience.
	 *
	 * @param primaryKey the primary key of this work experience
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this work experience.
	 *
	 * @return the uuid of this work experience
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this work experience.
	 *
	 * @param uuid the uuid of this work experience
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the work exp ID of this work experience.
	 *
	 * @return the work exp ID of this work experience
	 */
	public long getWorkExpId();

	/**
	 * Sets the work exp ID of this work experience.
	 *
	 * @param workExpId the work exp ID of this work experience
	 */
	public void setWorkExpId(long workExpId);

	/**
	 * Returns the work exp range of this work experience.
	 *
	 * @return the work exp range of this work experience
	 */
	@AutoEscape
	public String getWorkExpRange();

	/**
	 * Sets the work exp range of this work experience.
	 *
	 * @param workExpRange the work exp range of this work experience
	 */
	public void setWorkExpRange(String workExpRange);

	@Override
	public WorkExperience cloneWithOriginalValues();

}