/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.job.opening.service.service.base;

import com.job.opening.service.model.Jobinfo;
import com.job.opening.service.service.JobinfoLocalService;
import com.job.opening.service.service.JobinfoLocalServiceUtil;
import com.job.opening.service.service.persistence.AddressinfoPersistence;
import com.job.opening.service.service.persistence.DescriptiveinfoPersistence;
import com.job.opening.service.service.persistence.JobinfoPersistence;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the jobinfo local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.job.opening.service.service.impl.JobinfoLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.job.opening.service.service.impl.JobinfoLocalServiceImpl
 * @generated
 */
public abstract class JobinfoLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, JobinfoLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>JobinfoLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>JobinfoLocalServiceUtil</code>.
	 */

	/**
	 * Adds the jobinfo to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect JobinfoLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param jobinfo the jobinfo
	 * @return the jobinfo that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Jobinfo addJobinfo(Jobinfo jobinfo) {
		jobinfo.setNew(true);

		return jobinfoPersistence.update(jobinfo);
	}

	/**
	 * Creates a new jobinfo with the primary key. Does not add the jobinfo to the database.
	 *
	 * @param jobId the primary key for the new jobinfo
	 * @return the new jobinfo
	 */
	@Override
	@Transactional(enabled = false)
	public Jobinfo createJobinfo(long jobId) {
		return jobinfoPersistence.create(jobId);
	}

	/**
	 * Deletes the jobinfo with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect JobinfoLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param jobId the primary key of the jobinfo
	 * @return the jobinfo that was removed
	 * @throws PortalException if a jobinfo with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Jobinfo deleteJobinfo(long jobId) throws PortalException {
		return jobinfoPersistence.remove(jobId);
	}

	/**
	 * Deletes the jobinfo from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect JobinfoLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param jobinfo the jobinfo
	 * @return the jobinfo that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Jobinfo deleteJobinfo(Jobinfo jobinfo) {
		return jobinfoPersistence.remove(jobinfo);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return jobinfoPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			Jobinfo.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return jobinfoPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.job.opening.service.model.impl.JobinfoModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return jobinfoPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.job.opening.service.model.impl.JobinfoModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return jobinfoPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return jobinfoPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return jobinfoPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public Jobinfo fetchJobinfo(long jobId) {
		return jobinfoPersistence.fetchByPrimaryKey(jobId);
	}

	/**
	 * Returns the jobinfo matching the UUID and group.
	 *
	 * @param uuid the jobinfo's UUID
	 * @param groupId the primary key of the group
	 * @return the matching jobinfo, or <code>null</code> if a matching jobinfo could not be found
	 */
	@Override
	public Jobinfo fetchJobinfoByUuidAndGroupId(String uuid, long groupId) {
		return jobinfoPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the jobinfo with the primary key.
	 *
	 * @param jobId the primary key of the jobinfo
	 * @return the jobinfo
	 * @throws PortalException if a jobinfo with the primary key could not be found
	 */
	@Override
	public Jobinfo getJobinfo(long jobId) throws PortalException {
		return jobinfoPersistence.findByPrimaryKey(jobId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(jobinfoLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Jobinfo.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("jobId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			jobinfoLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(Jobinfo.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("jobId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(jobinfoLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Jobinfo.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("jobId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return jobinfoPersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return jobinfoLocalService.deleteJobinfo((Jobinfo)persistedModel);
	}

	@Override
	public BasePersistence<Jobinfo> getBasePersistence() {
		return jobinfoPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return jobinfoPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the jobinfos matching the UUID and company.
	 *
	 * @param uuid the UUID of the jobinfos
	 * @param companyId the primary key of the company
	 * @return the matching jobinfos, or an empty list if no matches were found
	 */
	@Override
	public List<Jobinfo> getJobinfosByUuidAndCompanyId(
		String uuid, long companyId) {

		return jobinfoPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of jobinfos matching the UUID and company.
	 *
	 * @param uuid the UUID of the jobinfos
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of jobinfos
	 * @param end the upper bound of the range of jobinfos (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching jobinfos, or an empty list if no matches were found
	 */
	@Override
	public List<Jobinfo> getJobinfosByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<Jobinfo> orderByComparator) {

		return jobinfoPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the jobinfo matching the UUID and group.
	 *
	 * @param uuid the jobinfo's UUID
	 * @param groupId the primary key of the group
	 * @return the matching jobinfo
	 * @throws PortalException if a matching jobinfo could not be found
	 */
	@Override
	public Jobinfo getJobinfoByUuidAndGroupId(String uuid, long groupId)
		throws PortalException {

		return jobinfoPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the jobinfos.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.job.opening.service.model.impl.JobinfoModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of jobinfos
	 * @param end the upper bound of the range of jobinfos (not inclusive)
	 * @return the range of jobinfos
	 */
	@Override
	public List<Jobinfo> getJobinfos(int start, int end) {
		return jobinfoPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of jobinfos.
	 *
	 * @return the number of jobinfos
	 */
	@Override
	public int getJobinfosCount() {
		return jobinfoPersistence.countAll();
	}

	/**
	 * Updates the jobinfo in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect JobinfoLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param jobinfo the jobinfo
	 * @return the jobinfo that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Jobinfo updateJobinfo(Jobinfo jobinfo) {
		return jobinfoPersistence.update(jobinfo);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			JobinfoLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		jobinfoLocalService = (JobinfoLocalService)aopProxy;

		_setLocalServiceUtilService(jobinfoLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return JobinfoLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Jobinfo.class;
	}

	protected String getModelClassName() {
		return Jobinfo.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = jobinfoPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		JobinfoLocalService jobinfoLocalService) {

		try {
			Field field = JobinfoLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, jobinfoLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected AddressinfoPersistence addressinfoPersistence;

	@Reference
	protected DescriptiveinfoPersistence descriptiveinfoPersistence;

	protected JobinfoLocalService jobinfoLocalService;

	@Reference
	protected JobinfoPersistence jobinfoPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}