/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.job.opening.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Addressinfo service. Represents a row in the &quot;rms_Addressinfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.job.opening.service.model.impl.AddressinfoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.job.opening.service.model.impl.AddressinfoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Addressinfo
 * @generated
 */
@ProviderType
public interface AddressinfoModel extends BaseModel<Addressinfo> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a addressinfo model instance should use the {@link Addressinfo} interface instead.
	 */

	/**
	 * Returns the primary key of this addressinfo.
	 *
	 * @return the primary key of this addressinfo
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this addressinfo.
	 *
	 * @param primaryKey the primary key of this addressinfo
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this addressinfo.
	 *
	 * @return the uuid of this addressinfo
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this addressinfo.
	 *
	 * @param uuid the uuid of this addressinfo
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the address ID of this addressinfo.
	 *
	 * @return the address ID of this addressinfo
	 */
	public long getAddressId();

	/**
	 * Sets the address ID of this addressinfo.
	 *
	 * @param addressId the address ID of this addressinfo
	 */
	public void setAddressId(long addressId);

	/**
	 * Returns the job ID of this addressinfo.
	 *
	 * @return the job ID of this addressinfo
	 */
	public long getJobId();

	/**
	 * Sets the job ID of this addressinfo.
	 *
	 * @param jobId the job ID of this addressinfo
	 */
	public void setJobId(long jobId);

	/**
	 * Returns the remote of this addressinfo.
	 *
	 * @return the remote of this addressinfo
	 */
	public boolean getRemote();

	/**
	 * Returns <code>true</code> if this addressinfo is remote.
	 *
	 * @return <code>true</code> if this addressinfo is remote; <code>false</code> otherwise
	 */
	public boolean isRemote();

	/**
	 * Sets whether this addressinfo is remote.
	 *
	 * @param remote the remote of this addressinfo
	 */
	public void setRemote(boolean remote);

	/**
	 * Returns the city of this addressinfo.
	 *
	 * @return the city of this addressinfo
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this addressinfo.
	 *
	 * @param city the city of this addressinfo
	 */
	public void setCity(String city);

	/**
	 * Returns the country of this addressinfo.
	 *
	 * @return the country of this addressinfo
	 */
	@AutoEscape
	public String getCountry();

	/**
	 * Sets the country of this addressinfo.
	 *
	 * @param country the country of this addressinfo
	 */
	public void setCountry(String country);

	/**
	 * Returns the state of this addressinfo.
	 *
	 * @return the state of this addressinfo
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this addressinfo.
	 *
	 * @param state the state of this addressinfo
	 */
	public void setState(String state);

	/**
	 * Returns the postal code of this addressinfo.
	 *
	 * @return the postal code of this addressinfo
	 */
	public long getPostalCode();

	/**
	 * Sets the postal code of this addressinfo.
	 *
	 * @param postalCode the postal code of this addressinfo
	 */
	public void setPostalCode(long postalCode);

	@Override
	public Addressinfo cloneWithOriginalValues();

}