/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.esquare.intranet.project.management.model.impl;

import com.esquare.intranet.project.management.model.ProjectManagement;
import com.esquare.intranet.project.management.model.ProjectManagementModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ProjectManagement service. Represents a row in the &quot;Esquare_ProjectManagement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ProjectManagementModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProjectManagementImpl}.
 * </p>
 *
 * @author Mahammed Seleem
 * @see ProjectManagementImpl
 * @generated
 */
@JSON(strict = true)
public class ProjectManagementModelImpl
	extends BaseModelImpl<ProjectManagement> implements ProjectManagementModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a project management model instance should use the <code>ProjectManagement</code> interface instead.
	 */
	public static final String TABLE_NAME = "Esquare_ProjectManagement";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"projectMgmtId", Types.BIGINT},
		{"name", Types.VARCHAR}, {"contactNumber", Types.VARCHAR},
		{"contactEmail", Types.VARCHAR}, {"projectName", Types.VARCHAR},
		{"description", Types.VARCHAR}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("projectMgmtId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contactNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contactEmail", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("projectName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Esquare_ProjectManagement (uuid_ VARCHAR(75) null,projectMgmtId LONG not null primary key,name VARCHAR(75) null,contactNumber VARCHAR(75) null,contactEmail VARCHAR(75) null,projectName VARCHAR(75) null,description VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table Esquare_ProjectManagement";

	public static final String ORDER_BY_JPQL =
		" ORDER BY projectManagement.projectMgmtId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Esquare_ProjectManagement.projectMgmtId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROJECTMGMTID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ProjectManagementModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _projectMgmtId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProjectMgmtId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _projectMgmtId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ProjectManagement.class;
	}

	@Override
	public String getModelClassName() {
		return ProjectManagement.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ProjectManagement, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ProjectManagement, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProjectManagement, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ProjectManagement)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ProjectManagement, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ProjectManagement, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ProjectManagement)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ProjectManagement, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ProjectManagement, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<ProjectManagement, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<ProjectManagement, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<ProjectManagement, Object>>();

			attributeGetterFunctions.put("uuid", ProjectManagement::getUuid);
			attributeGetterFunctions.put(
				"projectMgmtId", ProjectManagement::getProjectMgmtId);
			attributeGetterFunctions.put("name", ProjectManagement::getName);
			attributeGetterFunctions.put(
				"contactNumber", ProjectManagement::getContactNumber);
			attributeGetterFunctions.put(
				"contactEmail", ProjectManagement::getContactEmail);
			attributeGetterFunctions.put(
				"projectName", ProjectManagement::getProjectName);
			attributeGetterFunctions.put(
				"description", ProjectManagement::getDescription);
			attributeGetterFunctions.put(
				"groupId", ProjectManagement::getGroupId);
			attributeGetterFunctions.put(
				"companyId", ProjectManagement::getCompanyId);
			attributeGetterFunctions.put(
				"userId", ProjectManagement::getUserId);
			attributeGetterFunctions.put(
				"userName", ProjectManagement::getUserName);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<ProjectManagement, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<ProjectManagement, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<ProjectManagement, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<ProjectManagement, String>)
					ProjectManagement::setUuid);
			attributeSetterBiConsumers.put(
				"projectMgmtId",
				(BiConsumer<ProjectManagement, Long>)
					ProjectManagement::setProjectMgmtId);
			attributeSetterBiConsumers.put(
				"name",
				(BiConsumer<ProjectManagement, String>)
					ProjectManagement::setName);
			attributeSetterBiConsumers.put(
				"contactNumber",
				(BiConsumer<ProjectManagement, String>)
					ProjectManagement::setContactNumber);
			attributeSetterBiConsumers.put(
				"contactEmail",
				(BiConsumer<ProjectManagement, String>)
					ProjectManagement::setContactEmail);
			attributeSetterBiConsumers.put(
				"projectName",
				(BiConsumer<ProjectManagement, String>)
					ProjectManagement::setProjectName);
			attributeSetterBiConsumers.put(
				"description",
				(BiConsumer<ProjectManagement, String>)
					ProjectManagement::setDescription);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<ProjectManagement, Long>)
					ProjectManagement::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<ProjectManagement, Long>)
					ProjectManagement::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<ProjectManagement, Long>)
					ProjectManagement::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<ProjectManagement, String>)
					ProjectManagement::setUserName);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getProjectMgmtId() {
		return _projectMgmtId;
	}

	@Override
	public void setProjectMgmtId(long projectMgmtId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_projectMgmtId = projectMgmtId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public String getContactNumber() {
		if (_contactNumber == null) {
			return "";
		}
		else {
			return _contactNumber;
		}
	}

	@Override
	public void setContactNumber(String contactNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contactNumber = contactNumber;
	}

	@JSON
	@Override
	public String getContactEmail() {
		if (_contactEmail == null) {
			return "";
		}
		else {
			return _contactEmail;
		}
	}

	@Override
	public void setContactEmail(String contactEmail) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contactEmail = contactEmail;
	}

	@JSON
	@Override
	public String getProjectName() {
		if (_projectName == null) {
			return "";
		}
		else {
			return _projectName;
		}
	}

	@Override
	public void setProjectName(String projectName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_projectName = projectName;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ProjectManagement.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ProjectManagement toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ProjectManagement>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProjectManagementImpl projectManagementImpl =
			new ProjectManagementImpl();

		projectManagementImpl.setUuid(getUuid());
		projectManagementImpl.setProjectMgmtId(getProjectMgmtId());
		projectManagementImpl.setName(getName());
		projectManagementImpl.setContactNumber(getContactNumber());
		projectManagementImpl.setContactEmail(getContactEmail());
		projectManagementImpl.setProjectName(getProjectName());
		projectManagementImpl.setDescription(getDescription());
		projectManagementImpl.setGroupId(getGroupId());
		projectManagementImpl.setCompanyId(getCompanyId());
		projectManagementImpl.setUserId(getUserId());
		projectManagementImpl.setUserName(getUserName());

		projectManagementImpl.resetOriginalValues();

		return projectManagementImpl;
	}

	@Override
	public ProjectManagement cloneWithOriginalValues() {
		ProjectManagementImpl projectManagementImpl =
			new ProjectManagementImpl();

		projectManagementImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		projectManagementImpl.setProjectMgmtId(
			this.<Long>getColumnOriginalValue("projectMgmtId"));
		projectManagementImpl.setName(
			this.<String>getColumnOriginalValue("name"));
		projectManagementImpl.setContactNumber(
			this.<String>getColumnOriginalValue("contactNumber"));
		projectManagementImpl.setContactEmail(
			this.<String>getColumnOriginalValue("contactEmail"));
		projectManagementImpl.setProjectName(
			this.<String>getColumnOriginalValue("projectName"));
		projectManagementImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		projectManagementImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		projectManagementImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		projectManagementImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		projectManagementImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));

		return projectManagementImpl;
	}

	@Override
	public int compareTo(ProjectManagement projectManagement) {
		long primaryKey = projectManagement.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ProjectManagement)) {
			return false;
		}

		ProjectManagement projectManagement = (ProjectManagement)object;

		long primaryKey = projectManagement.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ProjectManagement> toCacheModel() {
		ProjectManagementCacheModel projectManagementCacheModel =
			new ProjectManagementCacheModel();

		projectManagementCacheModel.uuid = getUuid();

		String uuid = projectManagementCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			projectManagementCacheModel.uuid = null;
		}

		projectManagementCacheModel.projectMgmtId = getProjectMgmtId();

		projectManagementCacheModel.name = getName();

		String name = projectManagementCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			projectManagementCacheModel.name = null;
		}

		projectManagementCacheModel.contactNumber = getContactNumber();

		String contactNumber = projectManagementCacheModel.contactNumber;

		if ((contactNumber != null) && (contactNumber.length() == 0)) {
			projectManagementCacheModel.contactNumber = null;
		}

		projectManagementCacheModel.contactEmail = getContactEmail();

		String contactEmail = projectManagementCacheModel.contactEmail;

		if ((contactEmail != null) && (contactEmail.length() == 0)) {
			projectManagementCacheModel.contactEmail = null;
		}

		projectManagementCacheModel.projectName = getProjectName();

		String projectName = projectManagementCacheModel.projectName;

		if ((projectName != null) && (projectName.length() == 0)) {
			projectManagementCacheModel.projectName = null;
		}

		projectManagementCacheModel.description = getDescription();

		String description = projectManagementCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			projectManagementCacheModel.description = null;
		}

		projectManagementCacheModel.groupId = getGroupId();

		projectManagementCacheModel.companyId = getCompanyId();

		projectManagementCacheModel.userId = getUserId();

		projectManagementCacheModel.userName = getUserName();

		String userName = projectManagementCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			projectManagementCacheModel.userName = null;
		}

		return projectManagementCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ProjectManagement, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ProjectManagement, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProjectManagement, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ProjectManagement)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ProjectManagement>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ProjectManagement.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _projectMgmtId;
	private String _name;
	private String _contactNumber;
	private String _contactEmail;
	private String _projectName;
	private String _description;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ProjectManagement, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ProjectManagement)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("projectMgmtId", _projectMgmtId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("contactNumber", _contactNumber);
		_columnOriginalValues.put("contactEmail", _contactEmail);
		_columnOriginalValues.put("projectName", _projectName);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("projectMgmtId", 2L);

		columnBitmasks.put("name", 4L);

		columnBitmasks.put("contactNumber", 8L);

		columnBitmasks.put("contactEmail", 16L);

		columnBitmasks.put("projectName", 32L);

		columnBitmasks.put("description", 64L);

		columnBitmasks.put("groupId", 128L);

		columnBitmasks.put("companyId", 256L);

		columnBitmasks.put("userId", 512L);

		columnBitmasks.put("userName", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ProjectManagement _escapedModel;

}