/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package SendOtpService.service.base;

import SendOtpService.model.SendDb;

import SendOtpService.service.SendDbLocalService;
import SendOtpService.service.SendDbLocalServiceUtil;
import SendOtpService.service.persistence.SendDbPersistence;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the send db local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link SendOtpService.service.impl.SendDbLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SendOtpService.service.impl.SendDbLocalServiceImpl
 * @generated
 */
public abstract class SendDbLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, SendDbLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>SendDbLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>SendDbLocalServiceUtil</code>.
	 */

	/**
	 * Adds the send db to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect SendDbLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param sendDb the send db
	 * @return the send db that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public SendDb addSendDb(SendDb sendDb) {
		sendDb.setNew(true);

		return sendDbPersistence.update(sendDb);
	}

	/**
	 * Creates a new send db with the primary key. Does not add the send db to the database.
	 *
	 * @param sendId the primary key for the new send db
	 * @return the new send db
	 */
	@Override
	@Transactional(enabled = false)
	public SendDb createSendDb(long sendId) {
		return sendDbPersistence.create(sendId);
	}

	/**
	 * Deletes the send db with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect SendDbLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param sendId the primary key of the send db
	 * @return the send db that was removed
	 * @throws PortalException if a send db with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public SendDb deleteSendDb(long sendId) throws PortalException {
		return sendDbPersistence.remove(sendId);
	}

	/**
	 * Deletes the send db from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect SendDbLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param sendDb the send db
	 * @return the send db that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public SendDb deleteSendDb(SendDb sendDb) {
		return sendDbPersistence.remove(sendDb);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return sendDbPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			SendDb.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return sendDbPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>SendOtpService.model.impl.SendDbModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return sendDbPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>SendOtpService.model.impl.SendDbModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return sendDbPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return sendDbPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return sendDbPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public SendDb fetchSendDb(long sendId) {
		return sendDbPersistence.fetchByPrimaryKey(sendId);
	}

	/**
	 * Returns the send db with the matching UUID and company.
	 *
	 * @param uuid the send db's UUID
	 * @param companyId the primary key of the company
	 * @return the matching send db, or <code>null</code> if a matching send db could not be found
	 */
	@Override
	public SendDb fetchSendDbByUuidAndCompanyId(String uuid, long companyId) {
		return sendDbPersistence.fetchByUuid_C_First(uuid, companyId, null);
	}

	/**
	 * Returns the send db with the primary key.
	 *
	 * @param sendId the primary key of the send db
	 * @return the send db
	 * @throws PortalException if a send db with the primary key could not be found
	 */
	@Override
	public SendDb getSendDb(long sendId) throws PortalException {
		return sendDbPersistence.findByPrimaryKey(sendId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(sendDbLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(SendDb.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("sendId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(sendDbLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(SendDb.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("sendId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(sendDbLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(SendDb.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("sendId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return sendDbPersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return sendDbLocalService.deleteSendDb((SendDb)persistedModel);
	}

	@Override
	public BasePersistence<SendDb> getBasePersistence() {
		return sendDbPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return sendDbPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns the send db with the matching UUID and company.
	 *
	 * @param uuid the send db's UUID
	 * @param companyId the primary key of the company
	 * @return the matching send db
	 * @throws PortalException if a matching send db could not be found
	 */
	@Override
	public SendDb getSendDbByUuidAndCompanyId(String uuid, long companyId)
		throws PortalException {

		return sendDbPersistence.findByUuid_C_First(uuid, companyId, null);
	}

	/**
	 * Returns a range of all the send dbs.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>SendOtpService.model.impl.SendDbModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of send dbs
	 * @param end the upper bound of the range of send dbs (not inclusive)
	 * @return the range of send dbs
	 */
	@Override
	public List<SendDb> getSendDbs(int start, int end) {
		return sendDbPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of send dbs.
	 *
	 * @return the number of send dbs
	 */
	@Override
	public int getSendDbsCount() {
		return sendDbPersistence.countAll();
	}

	/**
	 * Updates the send db in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect SendDbLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param sendDb the send db
	 * @return the send db that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public SendDb updateSendDb(SendDb sendDb) {
		return sendDbPersistence.update(sendDb);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			SendDbLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		sendDbLocalService = (SendDbLocalService)aopProxy;

		_setLocalServiceUtilService(sendDbLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return SendDbLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return SendDb.class;
	}

	protected String getModelClassName() {
		return SendDb.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = sendDbPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		SendDbLocalService sendDbLocalService) {

		try {
			Field field = SendDbLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, sendDbLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	protected SendDbLocalService sendDbLocalService;

	@Reference
	protected SendDbPersistence sendDbPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetEntryLocalService
		assetEntryLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetTagLocalService
		assetTagLocalService;

}