/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.esquare.intranet.project.management.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Projects service. Represents a row in the &quot;Esquare_Projects&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.esquare.intranet.project.management.model.impl.ProjectsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.esquare.intranet.project.management.model.impl.ProjectsImpl</code>.
 * </p>
 *
 * @author Mahammed Seleem
 * @see Projects
 * @generated
 */
@ProviderType
public interface ProjectsModel extends BaseModel<Projects>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a projects model instance should use the {@link Projects} interface instead.
	 */

	/**
	 * Returns the primary key of this projects.
	 *
	 * @return the primary key of this projects
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this projects.
	 *
	 * @param primaryKey the primary key of this projects
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this projects.
	 *
	 * @return the uuid of this projects
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this projects.
	 *
	 * @param uuid the uuid of this projects
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the project ID of this projects.
	 *
	 * @return the project ID of this projects
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this projects.
	 *
	 * @param projectId the project ID of this projects
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the group ID of this projects.
	 *
	 * @return the group ID of this projects
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this projects.
	 *
	 * @param groupId the group ID of this projects
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this projects.
	 *
	 * @return the company ID of this projects
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this projects.
	 *
	 * @param companyId the company ID of this projects
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this projects.
	 *
	 * @return the user ID of this projects
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this projects.
	 *
	 * @param userId the user ID of this projects
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this projects.
	 *
	 * @return the user uuid of this projects
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this projects.
	 *
	 * @param userUuid the user uuid of this projects
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this projects.
	 *
	 * @return the user name of this projects
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this projects.
	 *
	 * @param userName the user name of this projects
	 */
	public void setUserName(String userName);

	/**
	 * Returns the project name of this projects.
	 *
	 * @return the project name of this projects
	 */
	@AutoEscape
	public String getProjectName();

	/**
	 * Sets the project name of this projects.
	 *
	 * @param projectName the project name of this projects
	 */
	public void setProjectName(String projectName);

	/**
	 * Returns the description of this projects.
	 *
	 * @return the description of this projects
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this projects.
	 *
	 * @param description the description of this projects
	 */
	public void setDescription(String description);

	/**
	 * Returns the proposed date of this projects.
	 *
	 * @return the proposed date of this projects
	 */
	public Date getProposedDate();

	/**
	 * Sets the proposed date of this projects.
	 *
	 * @param proposedDate the proposed date of this projects
	 */
	public void setProposedDate(Date proposedDate);

	/**
	 * Returns the confirmed date of this projects.
	 *
	 * @return the confirmed date of this projects
	 */
	public Date getConfirmedDate();

	/**
	 * Sets the confirmed date of this projects.
	 *
	 * @param confirmedDate the confirmed date of this projects
	 */
	public void setConfirmedDate(Date confirmedDate);

	/**
	 * Returns the development start date of this projects.
	 *
	 * @return the development start date of this projects
	 */
	public Date getDevelopmentStartDate();

	/**
	 * Sets the development start date of this projects.
	 *
	 * @param developmentStartDate the development start date of this projects
	 */
	public void setDevelopmentStartDate(Date developmentStartDate);

	/**
	 * Returns the estimated date of this projects.
	 *
	 * @return the estimated date of this projects
	 */
	public Date getEstimatedDate();

	/**
	 * Sets the estimated date of this projects.
	 *
	 * @param estimatedDate the estimated date of this projects
	 */
	public void setEstimatedDate(Date estimatedDate);

	/**
	 * Returns the duration date of this projects.
	 *
	 * @return the duration date of this projects
	 */
	@AutoEscape
	public String getDurationDate();

	/**
	 * Sets the duration date of this projects.
	 *
	 * @param durationDate the duration date of this projects
	 */
	public void setDurationDate(String durationDate);

	/**
	 * Returns the status of this projects.
	 *
	 * @return the status of this projects
	 */
	public int getStatus();

	/**
	 * Sets the status of this projects.
	 *
	 * @param status the status of this projects
	 */
	public void setStatus(int status);

	/**
	 * Returns the code of this projects.
	 *
	 * @return the code of this projects
	 */
	public int getCode();

	/**
	 * Sets the code of this projects.
	 *
	 * @param code the code of this projects
	 */
	public void setCode(int code);

	/**
	 * Returns the document ID of this projects.
	 *
	 * @return the document ID of this projects
	 */
	public long getDocumentId();

	/**
	 * Sets the document ID of this projects.
	 *
	 * @param documentId the document ID of this projects
	 */
	public void setDocumentId(long documentId);

	/**
	 * Returns the resource ID settings of this projects.
	 *
	 * @return the resource ID settings of this projects
	 */
	@AutoEscape
	public String getResourceIdSettings();

	/**
	 * Sets the resource ID settings of this projects.
	 *
	 * @param resourceIdSettings the resource ID settings of this projects
	 */
	public void setResourceIdSettings(String resourceIdSettings);

	/**
	 * Returns the name of this projects.
	 *
	 * @return the name of this projects
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this projects.
	 *
	 * @param name the name of this projects
	 */
	public void setName(String name);

	/**
	 * Returns the contact number of this projects.
	 *
	 * @return the contact number of this projects
	 */
	@AutoEscape
	public String getContactNumber();

	/**
	 * Sets the contact number of this projects.
	 *
	 * @param contactNumber the contact number of this projects
	 */
	public void setContactNumber(String contactNumber);

	/**
	 * Returns the contact email of this projects.
	 *
	 * @return the contact email of this projects
	 */
	@AutoEscape
	public String getContactEmail();

	/**
	 * Sets the contact email of this projects.
	 *
	 * @param contactEmail the contact email of this projects
	 */
	public void setContactEmail(String contactEmail);

	@Override
	public Projects cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}