/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.prime.data.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.prime.data.service.model.CandidateStatus;
import com.prime.data.service.model.CandidateStatusModel;
import com.prime.data.service.model.CandidateStatusSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CandidateStatus service. Represents a row in the &quot;PRIME_CandidateStatus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CandidateStatusModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CandidateStatusImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CandidateStatusImpl
 * @generated
 */
@JSON(strict = true)
public class CandidateStatusModelImpl
	extends BaseModelImpl<CandidateStatus> implements CandidateStatusModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a candidate status model instance should use the <code>CandidateStatus</code> interface instead.
	 */
	public static final String TABLE_NAME = "PRIME_CandidateStatus";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"candidateStatusId", Types.BIGINT},
		{"candidateStatus", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("candidateStatusId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("candidateStatus", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table PRIME_CandidateStatus (uuid_ VARCHAR(75) null,candidateStatusId LONG not null primary key,candidateStatus VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table PRIME_CandidateStatus";

	public static final String ORDER_BY_JPQL =
		" ORDER BY candidateStatus.candidateStatusId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY PRIME_CandidateStatus.candidateStatusId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CANDIDATESTATUSID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static CandidateStatus toModel(CandidateStatusSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CandidateStatus model = new CandidateStatusImpl();

		model.setUuid(soapModel.getUuid());
		model.setCandidateStatusId(soapModel.getCandidateStatusId());
		model.setCandidateStatus(soapModel.getCandidateStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<CandidateStatus> toModels(
		CandidateStatusSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<CandidateStatus> models = new ArrayList<CandidateStatus>(
			soapModels.length);

		for (CandidateStatusSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public CandidateStatusModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _candidateStatusId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCandidateStatusId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _candidateStatusId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CandidateStatus.class;
	}

	@Override
	public String getModelClassName() {
		return CandidateStatus.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CandidateStatus, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CandidateStatus, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CandidateStatus, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CandidateStatus)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CandidateStatus, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CandidateStatus, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CandidateStatus)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CandidateStatus, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CandidateStatus, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CandidateStatus>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CandidateStatus.class.getClassLoader(), CandidateStatus.class,
			ModelWrapper.class);

		try {
			Constructor<CandidateStatus> constructor =
				(Constructor<CandidateStatus>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<CandidateStatus, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CandidateStatus, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CandidateStatus, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<CandidateStatus, Object>>();
		Map<String, BiConsumer<CandidateStatus, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<CandidateStatus, ?>>();

		attributeGetterFunctions.put("uuid", CandidateStatus::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<CandidateStatus, String>)CandidateStatus::setUuid);
		attributeGetterFunctions.put(
			"candidateStatusId", CandidateStatus::getCandidateStatusId);
		attributeSetterBiConsumers.put(
			"candidateStatusId",
			(BiConsumer<CandidateStatus, Long>)
				CandidateStatus::setCandidateStatusId);
		attributeGetterFunctions.put(
			"candidateStatus", CandidateStatus::getCandidateStatus);
		attributeSetterBiConsumers.put(
			"candidateStatus",
			(BiConsumer<CandidateStatus, String>)
				CandidateStatus::setCandidateStatus);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCandidateStatusId() {
		return _candidateStatusId;
	}

	@Override
	public void setCandidateStatusId(long candidateStatusId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_candidateStatusId = candidateStatusId;
	}

	@JSON
	@Override
	public String getCandidateStatus() {
		if (_candidateStatus == null) {
			return "";
		}
		else {
			return _candidateStatus;
		}
	}

	@Override
	public void setCandidateStatus(String candidateStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_candidateStatus = candidateStatus;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, CandidateStatus.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CandidateStatus toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CandidateStatus>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CandidateStatusImpl candidateStatusImpl = new CandidateStatusImpl();

		candidateStatusImpl.setUuid(getUuid());
		candidateStatusImpl.setCandidateStatusId(getCandidateStatusId());
		candidateStatusImpl.setCandidateStatus(getCandidateStatus());

		candidateStatusImpl.resetOriginalValues();

		return candidateStatusImpl;
	}

	@Override
	public CandidateStatus cloneWithOriginalValues() {
		CandidateStatusImpl candidateStatusImpl = new CandidateStatusImpl();

		candidateStatusImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		candidateStatusImpl.setCandidateStatusId(
			this.<Long>getColumnOriginalValue("candidateStatusId"));
		candidateStatusImpl.setCandidateStatus(
			this.<String>getColumnOriginalValue("candidateStatus"));

		return candidateStatusImpl;
	}

	@Override
	public int compareTo(CandidateStatus candidateStatus) {
		long primaryKey = candidateStatus.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CandidateStatus)) {
			return false;
		}

		CandidateStatus candidateStatus = (CandidateStatus)object;

		long primaryKey = candidateStatus.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CandidateStatus> toCacheModel() {
		CandidateStatusCacheModel candidateStatusCacheModel =
			new CandidateStatusCacheModel();

		candidateStatusCacheModel.uuid = getUuid();

		String uuid = candidateStatusCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			candidateStatusCacheModel.uuid = null;
		}

		candidateStatusCacheModel.candidateStatusId = getCandidateStatusId();

		candidateStatusCacheModel.candidateStatus = getCandidateStatus();

		String candidateStatus = candidateStatusCacheModel.candidateStatus;

		if ((candidateStatus != null) && (candidateStatus.length() == 0)) {
			candidateStatusCacheModel.candidateStatus = null;
		}

		return candidateStatusCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CandidateStatus, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CandidateStatus, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CandidateStatus, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((CandidateStatus)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CandidateStatus, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CandidateStatus, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CandidateStatus, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CandidateStatus)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CandidateStatus>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _candidateStatusId;
	private String _candidateStatus;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<CandidateStatus, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CandidateStatus)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("candidateStatusId", _candidateStatusId);
		_columnOriginalValues.put("candidateStatus", _candidateStatus);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("candidateStatusId", 2L);

		columnBitmasks.put("candidateStatus", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CandidateStatus _escapedModel;

}