/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.prime.data.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.prime.data.service.model.CurrJobTitle;
import com.prime.data.service.model.CurrJobTitleModel;
import com.prime.data.service.model.CurrJobTitleSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CurrJobTitle service. Represents a row in the &quot;PRIME_CurrJobTitle&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CurrJobTitleModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CurrJobTitleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CurrJobTitleImpl
 * @generated
 */
@JSON(strict = true)
public class CurrJobTitleModelImpl
	extends BaseModelImpl<CurrJobTitle> implements CurrJobTitleModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a curr job title model instance should use the <code>CurrJobTitle</code> interface instead.
	 */
	public static final String TABLE_NAME = "PRIME_CurrJobTitle";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"currJobTitleId", Types.BIGINT},
		{"currentJobTitle", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("currJobTitleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("currentJobTitle", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table PRIME_CurrJobTitle (uuid_ VARCHAR(75) null,currJobTitleId LONG not null primary key,currentJobTitle VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table PRIME_CurrJobTitle";

	public static final String ORDER_BY_JPQL =
		" ORDER BY currJobTitle.currJobTitleId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY PRIME_CurrJobTitle.currJobTitleId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CURRJOBTITLEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static CurrJobTitle toModel(CurrJobTitleSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CurrJobTitle model = new CurrJobTitleImpl();

		model.setUuid(soapModel.getUuid());
		model.setCurrJobTitleId(soapModel.getCurrJobTitleId());
		model.setCurrentJobTitle(soapModel.getCurrentJobTitle());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<CurrJobTitle> toModels(CurrJobTitleSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CurrJobTitle> models = new ArrayList<CurrJobTitle>(
			soapModels.length);

		for (CurrJobTitleSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public CurrJobTitleModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _currJobTitleId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCurrJobTitleId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _currJobTitleId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CurrJobTitle.class;
	}

	@Override
	public String getModelClassName() {
		return CurrJobTitle.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CurrJobTitle, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CurrJobTitle, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CurrJobTitle, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CurrJobTitle)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CurrJobTitle, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CurrJobTitle, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CurrJobTitle)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CurrJobTitle, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CurrJobTitle, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CurrJobTitle>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CurrJobTitle.class.getClassLoader(), CurrJobTitle.class,
			ModelWrapper.class);

		try {
			Constructor<CurrJobTitle> constructor =
				(Constructor<CurrJobTitle>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<CurrJobTitle, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CurrJobTitle, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CurrJobTitle, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<CurrJobTitle, Object>>();
		Map<String, BiConsumer<CurrJobTitle, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<CurrJobTitle, ?>>();

		attributeGetterFunctions.put("uuid", CurrJobTitle::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<CurrJobTitle, String>)CurrJobTitle::setUuid);
		attributeGetterFunctions.put(
			"currJobTitleId", CurrJobTitle::getCurrJobTitleId);
		attributeSetterBiConsumers.put(
			"currJobTitleId",
			(BiConsumer<CurrJobTitle, Long>)CurrJobTitle::setCurrJobTitleId);
		attributeGetterFunctions.put(
			"currentJobTitle", CurrJobTitle::getCurrentJobTitle);
		attributeSetterBiConsumers.put(
			"currentJobTitle",
			(BiConsumer<CurrJobTitle, String>)CurrJobTitle::setCurrentJobTitle);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCurrJobTitleId() {
		return _currJobTitleId;
	}

	@Override
	public void setCurrJobTitleId(long currJobTitleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_currJobTitleId = currJobTitleId;
	}

	@JSON
	@Override
	public String getCurrentJobTitle() {
		if (_currentJobTitle == null) {
			return "";
		}
		else {
			return _currentJobTitle;
		}
	}

	@Override
	public void setCurrentJobTitle(String currentJobTitle) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_currentJobTitle = currentJobTitle;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, CurrJobTitle.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CurrJobTitle toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CurrJobTitle>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CurrJobTitleImpl currJobTitleImpl = new CurrJobTitleImpl();

		currJobTitleImpl.setUuid(getUuid());
		currJobTitleImpl.setCurrJobTitleId(getCurrJobTitleId());
		currJobTitleImpl.setCurrentJobTitle(getCurrentJobTitle());

		currJobTitleImpl.resetOriginalValues();

		return currJobTitleImpl;
	}

	@Override
	public CurrJobTitle cloneWithOriginalValues() {
		CurrJobTitleImpl currJobTitleImpl = new CurrJobTitleImpl();

		currJobTitleImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		currJobTitleImpl.setCurrJobTitleId(
			this.<Long>getColumnOriginalValue("currJobTitleId"));
		currJobTitleImpl.setCurrentJobTitle(
			this.<String>getColumnOriginalValue("currentJobTitle"));

		return currJobTitleImpl;
	}

	@Override
	public int compareTo(CurrJobTitle currJobTitle) {
		long primaryKey = currJobTitle.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CurrJobTitle)) {
			return false;
		}

		CurrJobTitle currJobTitle = (CurrJobTitle)object;

		long primaryKey = currJobTitle.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CurrJobTitle> toCacheModel() {
		CurrJobTitleCacheModel currJobTitleCacheModel =
			new CurrJobTitleCacheModel();

		currJobTitleCacheModel.uuid = getUuid();

		String uuid = currJobTitleCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			currJobTitleCacheModel.uuid = null;
		}

		currJobTitleCacheModel.currJobTitleId = getCurrJobTitleId();

		currJobTitleCacheModel.currentJobTitle = getCurrentJobTitle();

		String currentJobTitle = currJobTitleCacheModel.currentJobTitle;

		if ((currentJobTitle != null) && (currentJobTitle.length() == 0)) {
			currJobTitleCacheModel.currentJobTitle = null;
		}

		return currJobTitleCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CurrJobTitle, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CurrJobTitle, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CurrJobTitle, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((CurrJobTitle)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CurrJobTitle, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CurrJobTitle, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CurrJobTitle, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CurrJobTitle)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CurrJobTitle>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _currJobTitleId;
	private String _currentJobTitle;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<CurrJobTitle, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CurrJobTitle)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("currJobTitleId", _currJobTitleId);
		_columnOriginalValues.put("currentJobTitle", _currentJobTitle);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("currJobTitleId", 2L);

		columnBitmasks.put("currentJobTitle", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CurrJobTitle _escapedModel;

}