/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.prime.data.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.prime.data.service.model.InterviewName;
import com.prime.data.service.model.InterviewNameModel;
import com.prime.data.service.model.InterviewNameSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the InterviewName service. Represents a row in the &quot;PRIME_InterviewName&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>InterviewNameModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link InterviewNameImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see InterviewNameImpl
 * @generated
 */
@JSON(strict = true)
public class InterviewNameModelImpl
	extends BaseModelImpl<InterviewName> implements InterviewNameModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a interview name model instance should use the <code>InterviewName</code> interface instead.
	 */
	public static final String TABLE_NAME = "PRIME_InterviewName";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"interviewNameId", Types.BIGINT},
		{"interviewName", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("interviewNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("interviewName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table PRIME_InterviewName (uuid_ VARCHAR(75) null,interviewNameId LONG not null primary key,interviewName VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table PRIME_InterviewName";

	public static final String ORDER_BY_JPQL =
		" ORDER BY interviewName.interviewNameId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY PRIME_InterviewName.interviewNameId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long INTERVIEWNAMEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static InterviewName toModel(InterviewNameSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		InterviewName model = new InterviewNameImpl();

		model.setUuid(soapModel.getUuid());
		model.setInterviewNameId(soapModel.getInterviewNameId());
		model.setInterviewName(soapModel.getInterviewName());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<InterviewName> toModels(InterviewNameSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<InterviewName> models = new ArrayList<InterviewName>(
			soapModels.length);

		for (InterviewNameSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public InterviewNameModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _interviewNameId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setInterviewNameId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _interviewNameId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return InterviewName.class;
	}

	@Override
	public String getModelClassName() {
		return InterviewName.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<InterviewName, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<InterviewName, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<InterviewName, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((InterviewName)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<InterviewName, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<InterviewName, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(InterviewName)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<InterviewName, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<InterviewName, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, InterviewName>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			InterviewName.class.getClassLoader(), InterviewName.class,
			ModelWrapper.class);

		try {
			Constructor<InterviewName> constructor =
				(Constructor<InterviewName>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<InterviewName, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<InterviewName, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<InterviewName, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<InterviewName, Object>>();
		Map<String, BiConsumer<InterviewName, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<InterviewName, ?>>();

		attributeGetterFunctions.put("uuid", InterviewName::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<InterviewName, String>)InterviewName::setUuid);
		attributeGetterFunctions.put(
			"interviewNameId", InterviewName::getInterviewNameId);
		attributeSetterBiConsumers.put(
			"interviewNameId",
			(BiConsumer<InterviewName, Long>)InterviewName::setInterviewNameId);
		attributeGetterFunctions.put(
			"interviewName", InterviewName::getInterviewName);
		attributeSetterBiConsumers.put(
			"interviewName",
			(BiConsumer<InterviewName, String>)InterviewName::setInterviewName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getInterviewNameId() {
		return _interviewNameId;
	}

	@Override
	public void setInterviewNameId(long interviewNameId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_interviewNameId = interviewNameId;
	}

	@JSON
	@Override
	public String getInterviewName() {
		if (_interviewName == null) {
			return "";
		}
		else {
			return _interviewName;
		}
	}

	@Override
	public void setInterviewName(String interviewName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_interviewName = interviewName;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, InterviewName.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public InterviewName toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, InterviewName>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		InterviewNameImpl interviewNameImpl = new InterviewNameImpl();

		interviewNameImpl.setUuid(getUuid());
		interviewNameImpl.setInterviewNameId(getInterviewNameId());
		interviewNameImpl.setInterviewName(getInterviewName());

		interviewNameImpl.resetOriginalValues();

		return interviewNameImpl;
	}

	@Override
	public InterviewName cloneWithOriginalValues() {
		InterviewNameImpl interviewNameImpl = new InterviewNameImpl();

		interviewNameImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		interviewNameImpl.setInterviewNameId(
			this.<Long>getColumnOriginalValue("interviewNameId"));
		interviewNameImpl.setInterviewName(
			this.<String>getColumnOriginalValue("interviewName"));

		return interviewNameImpl;
	}

	@Override
	public int compareTo(InterviewName interviewName) {
		long primaryKey = interviewName.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof InterviewName)) {
			return false;
		}

		InterviewName interviewName = (InterviewName)object;

		long primaryKey = interviewName.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<InterviewName> toCacheModel() {
		InterviewNameCacheModel interviewNameCacheModel =
			new InterviewNameCacheModel();

		interviewNameCacheModel.uuid = getUuid();

		String uuid = interviewNameCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			interviewNameCacheModel.uuid = null;
		}

		interviewNameCacheModel.interviewNameId = getInterviewNameId();

		interviewNameCacheModel.interviewName = getInterviewName();

		String interviewName = interviewNameCacheModel.interviewName;

		if ((interviewName != null) && (interviewName.length() == 0)) {
			interviewNameCacheModel.interviewName = null;
		}

		return interviewNameCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<InterviewName, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<InterviewName, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<InterviewName, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((InterviewName)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<InterviewName, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<InterviewName, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<InterviewName, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((InterviewName)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, InterviewName>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _interviewNameId;
	private String _interviewName;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<InterviewName, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((InterviewName)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("interviewNameId", _interviewNameId);
		_columnOriginalValues.put("interviewName", _interviewName);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("interviewNameId", 2L);

		columnBitmasks.put("interviewName", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private InterviewName _escapedModel;

}