/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.prime.data.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.prime.data.service.model.SalesStage;
import com.prime.data.service.model.SalesStageModel;
import com.prime.data.service.model.SalesStageSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SalesStage service. Represents a row in the &quot;PRIME_SalesStage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SalesStageModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SalesStageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SalesStageImpl
 * @generated
 */
@JSON(strict = true)
public class SalesStageModelImpl
	extends BaseModelImpl<SalesStage> implements SalesStageModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sales stage model instance should use the <code>SalesStage</code> interface instead.
	 */
	public static final String TABLE_NAME = "PRIME_SalesStage";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"salesStageId", Types.BIGINT},
		{"salesStage", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("salesStageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("salesStage", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table PRIME_SalesStage (uuid_ VARCHAR(75) null,salesStageId LONG not null primary key,salesStage VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table PRIME_SalesStage";

	public static final String ORDER_BY_JPQL =
		" ORDER BY salesStage.salesStageId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY PRIME_SalesStage.salesStageId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SALESSTAGEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static SalesStage toModel(SalesStageSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SalesStage model = new SalesStageImpl();

		model.setUuid(soapModel.getUuid());
		model.setSalesStageId(soapModel.getSalesStageId());
		model.setSalesStage(soapModel.getSalesStage());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<SalesStage> toModels(SalesStageSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<SalesStage> models = new ArrayList<SalesStage>(soapModels.length);

		for (SalesStageSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public SalesStageModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _salesStageId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSalesStageId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _salesStageId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SalesStage.class;
	}

	@Override
	public String getModelClassName() {
		return SalesStage.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SalesStage, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SalesStage, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SalesStage, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((SalesStage)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SalesStage, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SalesStage, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SalesStage)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SalesStage, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SalesStage, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, SalesStage>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			SalesStage.class.getClassLoader(), SalesStage.class,
			ModelWrapper.class);

		try {
			Constructor<SalesStage> constructor =
				(Constructor<SalesStage>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<SalesStage, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SalesStage, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SalesStage, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<SalesStage, Object>>();
		Map<String, BiConsumer<SalesStage, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<SalesStage, ?>>();

		attributeGetterFunctions.put("uuid", SalesStage::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<SalesStage, String>)SalesStage::setUuid);
		attributeGetterFunctions.put(
			"salesStageId", SalesStage::getSalesStageId);
		attributeSetterBiConsumers.put(
			"salesStageId",
			(BiConsumer<SalesStage, Long>)SalesStage::setSalesStageId);
		attributeGetterFunctions.put("salesStage", SalesStage::getSalesStage);
		attributeSetterBiConsumers.put(
			"salesStage",
			(BiConsumer<SalesStage, String>)SalesStage::setSalesStage);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getSalesStageId() {
		return _salesStageId;
	}

	@Override
	public void setSalesStageId(long salesStageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_salesStageId = salesStageId;
	}

	@JSON
	@Override
	public String getSalesStage() {
		if (_salesStage == null) {
			return "";
		}
		else {
			return _salesStage;
		}
	}

	@Override
	public void setSalesStage(String salesStage) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_salesStage = salesStage;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, SalesStage.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SalesStage toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SalesStage>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SalesStageImpl salesStageImpl = new SalesStageImpl();

		salesStageImpl.setUuid(getUuid());
		salesStageImpl.setSalesStageId(getSalesStageId());
		salesStageImpl.setSalesStage(getSalesStage());

		salesStageImpl.resetOriginalValues();

		return salesStageImpl;
	}

	@Override
	public SalesStage cloneWithOriginalValues() {
		SalesStageImpl salesStageImpl = new SalesStageImpl();

		salesStageImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		salesStageImpl.setSalesStageId(
			this.<Long>getColumnOriginalValue("salesStageId"));
		salesStageImpl.setSalesStage(
			this.<String>getColumnOriginalValue("salesStage"));

		return salesStageImpl;
	}

	@Override
	public int compareTo(SalesStage salesStage) {
		long primaryKey = salesStage.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SalesStage)) {
			return false;
		}

		SalesStage salesStage = (SalesStage)object;

		long primaryKey = salesStage.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SalesStage> toCacheModel() {
		SalesStageCacheModel salesStageCacheModel = new SalesStageCacheModel();

		salesStageCacheModel.uuid = getUuid();

		String uuid = salesStageCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			salesStageCacheModel.uuid = null;
		}

		salesStageCacheModel.salesStageId = getSalesStageId();

		salesStageCacheModel.salesStage = getSalesStage();

		String salesStage = salesStageCacheModel.salesStage;

		if ((salesStage != null) && (salesStage.length() == 0)) {
			salesStageCacheModel.salesStage = null;
		}

		return salesStageCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SalesStage, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SalesStage, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SalesStage, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((SalesStage)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<SalesStage, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<SalesStage, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SalesStage, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((SalesStage)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SalesStage>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _salesStageId;
	private String _salesStage;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<SalesStage, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SalesStage)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("salesStageId", _salesStageId);
		_columnOriginalValues.put("salesStage", _salesStage);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("salesStageId", 2L);

		columnBitmasks.put("salesStage", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SalesStage _escapedModel;

}