/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.prime.data.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.prime.data.service.model.SkillSet;
import com.prime.data.service.model.SkillSetModel;
import com.prime.data.service.model.SkillSetSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SkillSet service. Represents a row in the &quot;PRIME_SkillSet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SkillSetModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SkillSetImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SkillSetImpl
 * @generated
 */
@JSON(strict = true)
public class SkillSetModelImpl
	extends BaseModelImpl<SkillSet> implements SkillSetModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a skill set model instance should use the <code>SkillSet</code> interface instead.
	 */
	public static final String TABLE_NAME = "PRIME_SkillSet";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"skillSetId", Types.BIGINT},
		{"skillCategory", Types.VARCHAR}, {"skillCategoryTools", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("skillSetId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("skillCategory", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("skillCategoryTools", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table PRIME_SkillSet (uuid_ VARCHAR(75) null,skillSetId LONG not null primary key,skillCategory VARCHAR(75) null,skillCategoryTools VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table PRIME_SkillSet";

	public static final String ORDER_BY_JPQL =
		" ORDER BY skillSet.skillSetId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY PRIME_SkillSet.skillSetId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SKILLSETID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static SkillSet toModel(SkillSetSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SkillSet model = new SkillSetImpl();

		model.setUuid(soapModel.getUuid());
		model.setSkillSetId(soapModel.getSkillSetId());
		model.setSkillCategory(soapModel.getSkillCategory());
		model.setSkillCategoryTools(soapModel.getSkillCategoryTools());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<SkillSet> toModels(SkillSetSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<SkillSet> models = new ArrayList<SkillSet>(soapModels.length);

		for (SkillSetSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public SkillSetModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _skillSetId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSkillSetId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _skillSetId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SkillSet.class;
	}

	@Override
	public String getModelClassName() {
		return SkillSet.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SkillSet, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SkillSet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SkillSet, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((SkillSet)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SkillSet, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SkillSet, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SkillSet)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SkillSet, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SkillSet, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, SkillSet>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			SkillSet.class.getClassLoader(), SkillSet.class,
			ModelWrapper.class);

		try {
			Constructor<SkillSet> constructor =
				(Constructor<SkillSet>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<SkillSet, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SkillSet, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SkillSet, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<SkillSet, Object>>();
		Map<String, BiConsumer<SkillSet, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<SkillSet, ?>>();

		attributeGetterFunctions.put("uuid", SkillSet::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<SkillSet, String>)SkillSet::setUuid);
		attributeGetterFunctions.put("skillSetId", SkillSet::getSkillSetId);
		attributeSetterBiConsumers.put(
			"skillSetId", (BiConsumer<SkillSet, Long>)SkillSet::setSkillSetId);
		attributeGetterFunctions.put(
			"skillCategory", SkillSet::getSkillCategory);
		attributeSetterBiConsumers.put(
			"skillCategory",
			(BiConsumer<SkillSet, String>)SkillSet::setSkillCategory);
		attributeGetterFunctions.put(
			"skillCategoryTools", SkillSet::getSkillCategoryTools);
		attributeSetterBiConsumers.put(
			"skillCategoryTools",
			(BiConsumer<SkillSet, String>)SkillSet::setSkillCategoryTools);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getSkillSetId() {
		return _skillSetId;
	}

	@Override
	public void setSkillSetId(long skillSetId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_skillSetId = skillSetId;
	}

	@JSON
	@Override
	public String getSkillCategory() {
		if (_skillCategory == null) {
			return "";
		}
		else {
			return _skillCategory;
		}
	}

	@Override
	public void setSkillCategory(String skillCategory) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_skillCategory = skillCategory;
	}

	@JSON
	@Override
	public String getSkillCategoryTools() {
		if (_skillCategoryTools == null) {
			return "";
		}
		else {
			return _skillCategoryTools;
		}
	}

	@Override
	public void setSkillCategoryTools(String skillCategoryTools) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_skillCategoryTools = skillCategoryTools;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, SkillSet.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SkillSet toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SkillSet>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SkillSetImpl skillSetImpl = new SkillSetImpl();

		skillSetImpl.setUuid(getUuid());
		skillSetImpl.setSkillSetId(getSkillSetId());
		skillSetImpl.setSkillCategory(getSkillCategory());
		skillSetImpl.setSkillCategoryTools(getSkillCategoryTools());

		skillSetImpl.resetOriginalValues();

		return skillSetImpl;
	}

	@Override
	public SkillSet cloneWithOriginalValues() {
		SkillSetImpl skillSetImpl = new SkillSetImpl();

		skillSetImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		skillSetImpl.setSkillSetId(
			this.<Long>getColumnOriginalValue("skillSetId"));
		skillSetImpl.setSkillCategory(
			this.<String>getColumnOriginalValue("skillCategory"));
		skillSetImpl.setSkillCategoryTools(
			this.<String>getColumnOriginalValue("skillCategoryTools"));

		return skillSetImpl;
	}

	@Override
	public int compareTo(SkillSet skillSet) {
		long primaryKey = skillSet.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SkillSet)) {
			return false;
		}

		SkillSet skillSet = (SkillSet)object;

		long primaryKey = skillSet.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SkillSet> toCacheModel() {
		SkillSetCacheModel skillSetCacheModel = new SkillSetCacheModel();

		skillSetCacheModel.uuid = getUuid();

		String uuid = skillSetCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			skillSetCacheModel.uuid = null;
		}

		skillSetCacheModel.skillSetId = getSkillSetId();

		skillSetCacheModel.skillCategory = getSkillCategory();

		String skillCategory = skillSetCacheModel.skillCategory;

		if ((skillCategory != null) && (skillCategory.length() == 0)) {
			skillSetCacheModel.skillCategory = null;
		}

		skillSetCacheModel.skillCategoryTools = getSkillCategoryTools();

		String skillCategoryTools = skillSetCacheModel.skillCategoryTools;

		if ((skillCategoryTools != null) &&
			(skillCategoryTools.length() == 0)) {

			skillSetCacheModel.skillCategoryTools = null;
		}

		return skillSetCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SkillSet, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SkillSet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SkillSet, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((SkillSet)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<SkillSet, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<SkillSet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SkillSet, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((SkillSet)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SkillSet>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _skillSetId;
	private String _skillCategory;
	private String _skillCategoryTools;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<SkillSet, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SkillSet)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("skillSetId", _skillSetId);
		_columnOriginalValues.put("skillCategory", _skillCategory);
		_columnOriginalValues.put("skillCategoryTools", _skillCategoryTools);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("skillSetId", 2L);

		columnBitmasks.put("skillCategory", 4L);

		columnBitmasks.put("skillCategoryTools", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SkillSet _escapedModel;

}