/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.candidate.service.service.base;

import com.candidate.service.model.CandidateInfo;
import com.candidate.service.service.CandidateInfoLocalService;
import com.candidate.service.service.CandidateInfoLocalServiceUtil;
import com.candidate.service.service.persistence.CandidateInfoPersistence;
import com.candidate.service.service.persistence.CandidateOtherInfoPersistence;
import com.candidate.service.service.persistence.ProfessionalDetailsPersistence;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the candidate info local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.candidate.service.service.impl.CandidateInfoLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.candidate.service.service.impl.CandidateInfoLocalServiceImpl
 * @generated
 */
public abstract class CandidateInfoLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, CandidateInfoLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CandidateInfoLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>CandidateInfoLocalServiceUtil</code>.
	 */

	/**
	 * Adds the candidate info to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CandidateInfoLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param candidateInfo the candidate info
	 * @return the candidate info that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CandidateInfo addCandidateInfo(CandidateInfo candidateInfo) {
		candidateInfo.setNew(true);

		return candidateInfoPersistence.update(candidateInfo);
	}

	/**
	 * Creates a new candidate info with the primary key. Does not add the candidate info to the database.
	 *
	 * @param candidateId the primary key for the new candidate info
	 * @return the new candidate info
	 */
	@Override
	@Transactional(enabled = false)
	public CandidateInfo createCandidateInfo(long candidateId) {
		return candidateInfoPersistence.create(candidateId);
	}

	/**
	 * Deletes the candidate info with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CandidateInfoLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param candidateId the primary key of the candidate info
	 * @return the candidate info that was removed
	 * @throws PortalException if a candidate info with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CandidateInfo deleteCandidateInfo(long candidateId)
		throws PortalException {

		return candidateInfoPersistence.remove(candidateId);
	}

	/**
	 * Deletes the candidate info from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CandidateInfoLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param candidateInfo the candidate info
	 * @return the candidate info that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CandidateInfo deleteCandidateInfo(CandidateInfo candidateInfo) {
		return candidateInfoPersistence.remove(candidateInfo);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return candidateInfoPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			CandidateInfo.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return candidateInfoPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.candidate.service.model.impl.CandidateInfoModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return candidateInfoPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.candidate.service.model.impl.CandidateInfoModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return candidateInfoPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return candidateInfoPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return candidateInfoPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public CandidateInfo fetchCandidateInfo(long candidateId) {
		return candidateInfoPersistence.fetchByPrimaryKey(candidateId);
	}

	/**
	 * Returns the candidate info with the matching UUID and company.
	 *
	 * @param uuid the candidate info's UUID
	 * @param companyId the primary key of the company
	 * @return the matching candidate info, or <code>null</code> if a matching candidate info could not be found
	 */
	@Override
	public CandidateInfo fetchCandidateInfoByUuidAndCompanyId(
		String uuid, long companyId) {

		return candidateInfoPersistence.fetchByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns the candidate info with the primary key.
	 *
	 * @param candidateId the primary key of the candidate info
	 * @return the candidate info
	 * @throws PortalException if a candidate info with the primary key could not be found
	 */
	@Override
	public CandidateInfo getCandidateInfo(long candidateId)
		throws PortalException {

		return candidateInfoPersistence.findByPrimaryKey(candidateId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(candidateInfoLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CandidateInfo.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("candidateId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			candidateInfoLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(CandidateInfo.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"candidateId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(candidateInfoLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CandidateInfo.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("candidateId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return candidateInfoPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return candidateInfoLocalService.deleteCandidateInfo(
			(CandidateInfo)persistedModel);
	}

	@Override
	public BasePersistence<CandidateInfo> getBasePersistence() {
		return candidateInfoPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return candidateInfoPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns the candidate info with the matching UUID and company.
	 *
	 * @param uuid the candidate info's UUID
	 * @param companyId the primary key of the company
	 * @return the matching candidate info
	 * @throws PortalException if a matching candidate info could not be found
	 */
	@Override
	public CandidateInfo getCandidateInfoByUuidAndCompanyId(
			String uuid, long companyId)
		throws PortalException {

		return candidateInfoPersistence.findByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns a range of all the candidate infos.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.candidate.service.model.impl.CandidateInfoModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of candidate infos
	 * @param end the upper bound of the range of candidate infos (not inclusive)
	 * @return the range of candidate infos
	 */
	@Override
	public List<CandidateInfo> getCandidateInfos(int start, int end) {
		return candidateInfoPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of candidate infos.
	 *
	 * @return the number of candidate infos
	 */
	@Override
	public int getCandidateInfosCount() {
		return candidateInfoPersistence.countAll();
	}

	/**
	 * Updates the candidate info in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CandidateInfoLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param candidateInfo the candidate info
	 * @return the candidate info that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CandidateInfo updateCandidateInfo(CandidateInfo candidateInfo) {
		return candidateInfoPersistence.update(candidateInfo);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			CandidateInfoLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		candidateInfoLocalService = (CandidateInfoLocalService)aopProxy;

		_setLocalServiceUtilService(candidateInfoLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CandidateInfoLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return CandidateInfo.class;
	}

	protected String getModelClassName() {
		return CandidateInfo.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = candidateInfoPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		CandidateInfoLocalService candidateInfoLocalService) {

		try {
			Field field = CandidateInfoLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, candidateInfoLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	protected CandidateInfoLocalService candidateInfoLocalService;

	@Reference
	protected CandidateInfoPersistence candidateInfoPersistence;

	@Reference
	protected CandidateOtherInfoPersistence candidateOtherInfoPersistence;

	@Reference
	protected ProfessionalDetailsPersistence professionalDetailsPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.WorkflowInstanceLinkLocalService
		workflowInstanceLinkLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetEntryLocalService
		assetEntryLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetTagLocalService
		assetTagLocalService;

}