/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package api.master.slayer.model.impl;

import api.master.slayer.model.ApiMapKey;
import api.master.slayer.model.ApiMapKeyModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ApiMapKey service. Represents a row in the &quot;API_ApiMapKey&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ApiMapKeyModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ApiMapKeyImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ApiMapKeyImpl
 * @generated
 */
@JSON(strict = true)
public class ApiMapKeyModelImpl
	extends BaseModelImpl<ApiMapKey> implements ApiMapKeyModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a api map key model instance should use the <code>ApiMapKey</code> interface instead.
	 */
	public static final String TABLE_NAME = "API_ApiMapKey";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"apiMapKeyId", Types.BIGINT},
		{"name", Types.VARCHAR}, {"key_", Types.VARCHAR},
		{"typeSettings", Types.VARCHAR}, {"userId", Types.BIGINT},
		{"groupId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("apiMapKeyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("key_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("typeSettings", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table API_ApiMapKey (uuid_ VARCHAR(75) null,apiMapKeyId LONG not null primary key,name VARCHAR(75) null,key_ STRING null,typeSettings STRING null,userId LONG,groupId LONG)";

	public static final String TABLE_SQL_DROP = "drop table API_ApiMapKey";

	public static final String ORDER_BY_JPQL =
		" ORDER BY apiMapKey.apiMapKeyId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY API_ApiMapKey.apiMapKeyId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long APIMAPKEYID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ApiMapKeyModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _apiMapKeyId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setApiMapKeyId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _apiMapKeyId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ApiMapKey.class;
	}

	@Override
	public String getModelClassName() {
		return ApiMapKey.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ApiMapKey, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ApiMapKey, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ApiMapKey, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((ApiMapKey)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ApiMapKey, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ApiMapKey, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ApiMapKey)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ApiMapKey, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ApiMapKey, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<ApiMapKey, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<ApiMapKey, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<ApiMapKey, Object>>();

			attributeGetterFunctions.put("uuid", ApiMapKey::getUuid);
			attributeGetterFunctions.put(
				"apiMapKeyId", ApiMapKey::getApiMapKeyId);
			attributeGetterFunctions.put("name", ApiMapKey::getName);
			attributeGetterFunctions.put("key", ApiMapKey::getKey);
			attributeGetterFunctions.put(
				"typeSettings", ApiMapKey::getTypeSettings);
			attributeGetterFunctions.put("userId", ApiMapKey::getUserId);
			attributeGetterFunctions.put("groupId", ApiMapKey::getGroupId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<ApiMapKey, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<ApiMapKey, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<ApiMapKey, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<ApiMapKey, String>)ApiMapKey::setUuid);
			attributeSetterBiConsumers.put(
				"apiMapKeyId",
				(BiConsumer<ApiMapKey, Long>)ApiMapKey::setApiMapKeyId);
			attributeSetterBiConsumers.put(
				"name", (BiConsumer<ApiMapKey, String>)ApiMapKey::setName);
			attributeSetterBiConsumers.put(
				"key", (BiConsumer<ApiMapKey, String>)ApiMapKey::setKey);
			attributeSetterBiConsumers.put(
				"typeSettings",
				(BiConsumer<ApiMapKey, String>)ApiMapKey::setTypeSettings);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<ApiMapKey, Long>)ApiMapKey::setUserId);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<ApiMapKey, Long>)ApiMapKey::setGroupId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getApiMapKeyId() {
		return _apiMapKeyId;
	}

	@Override
	public void setApiMapKeyId(long apiMapKeyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_apiMapKeyId = apiMapKeyId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	@JSON
	@Override
	public String getKey() {
		if (_key == null) {
			return "";
		}
		else {
			return _key;
		}
	}

	@Override
	public void setKey(String key) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_key = key;
	}

	@JSON
	@Override
	public String getTypeSettings() {
		if (_typeSettings == null) {
			return "";
		}
		else {
			return _typeSettings;
		}
	}

	@Override
	public void setTypeSettings(String typeSettings) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_typeSettings = typeSettings;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ApiMapKey.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ApiMapKey toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ApiMapKey>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ApiMapKeyImpl apiMapKeyImpl = new ApiMapKeyImpl();

		apiMapKeyImpl.setUuid(getUuid());
		apiMapKeyImpl.setApiMapKeyId(getApiMapKeyId());
		apiMapKeyImpl.setName(getName());
		apiMapKeyImpl.setKey(getKey());
		apiMapKeyImpl.setTypeSettings(getTypeSettings());
		apiMapKeyImpl.setUserId(getUserId());
		apiMapKeyImpl.setGroupId(getGroupId());

		apiMapKeyImpl.resetOriginalValues();

		return apiMapKeyImpl;
	}

	@Override
	public ApiMapKey cloneWithOriginalValues() {
		ApiMapKeyImpl apiMapKeyImpl = new ApiMapKeyImpl();

		apiMapKeyImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		apiMapKeyImpl.setApiMapKeyId(
			this.<Long>getColumnOriginalValue("apiMapKeyId"));
		apiMapKeyImpl.setName(this.<String>getColumnOriginalValue("name"));
		apiMapKeyImpl.setKey(this.<String>getColumnOriginalValue("key_"));
		apiMapKeyImpl.setTypeSettings(
			this.<String>getColumnOriginalValue("typeSettings"));
		apiMapKeyImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		apiMapKeyImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));

		return apiMapKeyImpl;
	}

	@Override
	public int compareTo(ApiMapKey apiMapKey) {
		long primaryKey = apiMapKey.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ApiMapKey)) {
			return false;
		}

		ApiMapKey apiMapKey = (ApiMapKey)object;

		long primaryKey = apiMapKey.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ApiMapKey> toCacheModel() {
		ApiMapKeyCacheModel apiMapKeyCacheModel = new ApiMapKeyCacheModel();

		apiMapKeyCacheModel.uuid = getUuid();

		String uuid = apiMapKeyCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			apiMapKeyCacheModel.uuid = null;
		}

		apiMapKeyCacheModel.apiMapKeyId = getApiMapKeyId();

		apiMapKeyCacheModel.name = getName();

		String name = apiMapKeyCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			apiMapKeyCacheModel.name = null;
		}

		apiMapKeyCacheModel.key = getKey();

		String key = apiMapKeyCacheModel.key;

		if ((key != null) && (key.length() == 0)) {
			apiMapKeyCacheModel.key = null;
		}

		apiMapKeyCacheModel.typeSettings = getTypeSettings();

		String typeSettings = apiMapKeyCacheModel.typeSettings;

		if ((typeSettings != null) && (typeSettings.length() == 0)) {
			apiMapKeyCacheModel.typeSettings = null;
		}

		apiMapKeyCacheModel.userId = getUserId();

		apiMapKeyCacheModel.groupId = getGroupId();

		return apiMapKeyCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ApiMapKey, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ApiMapKey, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ApiMapKey, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ApiMapKey)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ApiMapKey>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ApiMapKey.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _apiMapKeyId;
	private String _name;
	private String _key;
	private String _typeSettings;
	private long _userId;
	private long _groupId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ApiMapKey, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ApiMapKey)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("apiMapKeyId", _apiMapKeyId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("key_", _key);
		_columnOriginalValues.put("typeSettings", _typeSettings);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("groupId", _groupId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("key_", "key");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("apiMapKeyId", 2L);

		columnBitmasks.put("name", 4L);

		columnBitmasks.put("key_", 8L);

		columnBitmasks.put("typeSettings", 16L);

		columnBitmasks.put("userId", 32L);

		columnBitmasks.put("groupId", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ApiMapKey _escapedModel;

}