/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package api.master.slayer.model.impl;

import api.master.slayer.model.ConnectedAccounts;
import api.master.slayer.service.ConnectedAccountsLocalServiceUtil;

/**
 * The extended model base implementation for the ConnectedAccounts service. Represents a row in the &quot;API_ConnectedAccounts&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ConnectedAccountsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ConnectedAccountsImpl
 * @see ConnectedAccounts
 * @generated
 */
public abstract class ConnectedAccountsBaseImpl
	extends ConnectedAccountsModelImpl implements ConnectedAccounts {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a connected accounts model instance should use the <code>ConnectedAccounts</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ConnectedAccountsLocalServiceUtil.addConnectedAccounts(this);
		}
		else {
			ConnectedAccountsLocalServiceUtil.updateConnectedAccounts(this);
		}
	}

}