/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package api.master.slayer.model.impl;

import api.master.slayer.model.MasterUrl;
import api.master.slayer.model.MasterUrlModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MasterUrl service. Represents a row in the &quot;API_MasterUrl&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MasterUrlModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MasterUrlImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MasterUrlImpl
 * @generated
 */
@JSON(strict = true)
public class MasterUrlModelImpl
	extends BaseModelImpl<MasterUrl> implements MasterUrlModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a master url model instance should use the <code>MasterUrl</code> interface instead.
	 */
	public static final String TABLE_NAME = "API_MasterUrl";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"masterUrlId", Types.BIGINT},
		{"appName", Types.VARCHAR}, {"baseUrl", Types.VARCHAR},
		{"svgIcon", Types.VARCHAR}, {"userId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("masterUrlId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("appName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("baseUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("svgIcon", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table API_MasterUrl (uuid_ VARCHAR(75) null,masterUrlId LONG not null primary key,appName VARCHAR(75) null,baseUrl VARCHAR(75) null,svgIcon VARCHAR(75) null,userId LONG,groupId LONG,companyId LONG,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table API_MasterUrl";

	public static final String ORDER_BY_JPQL =
		" ORDER BY masterUrl.masterUrlId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY API_MasterUrl.masterUrlId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long APPNAME_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MASTERURLID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public MasterUrlModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _masterUrlId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMasterUrlId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _masterUrlId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MasterUrl.class;
	}

	@Override
	public String getModelClassName() {
		return MasterUrl.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MasterUrl, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MasterUrl, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MasterUrl, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((MasterUrl)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MasterUrl, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MasterUrl, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MasterUrl)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MasterUrl, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MasterUrl, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<MasterUrl, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<MasterUrl, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<MasterUrl, Object>>();

			attributeGetterFunctions.put("uuid", MasterUrl::getUuid);
			attributeGetterFunctions.put(
				"masterUrlId", MasterUrl::getMasterUrlId);
			attributeGetterFunctions.put("appName", MasterUrl::getAppName);
			attributeGetterFunctions.put("baseUrl", MasterUrl::getBaseUrl);
			attributeGetterFunctions.put("svgIcon", MasterUrl::getSvgIcon);
			attributeGetterFunctions.put("userId", MasterUrl::getUserId);
			attributeGetterFunctions.put("groupId", MasterUrl::getGroupId);
			attributeGetterFunctions.put("companyId", MasterUrl::getCompanyId);
			attributeGetterFunctions.put(
				"createDate", MasterUrl::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", MasterUrl::getModifiedDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<MasterUrl, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<MasterUrl, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<MasterUrl, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<MasterUrl, String>)MasterUrl::setUuid);
			attributeSetterBiConsumers.put(
				"masterUrlId",
				(BiConsumer<MasterUrl, Long>)MasterUrl::setMasterUrlId);
			attributeSetterBiConsumers.put(
				"appName",
				(BiConsumer<MasterUrl, String>)MasterUrl::setAppName);
			attributeSetterBiConsumers.put(
				"baseUrl",
				(BiConsumer<MasterUrl, String>)MasterUrl::setBaseUrl);
			attributeSetterBiConsumers.put(
				"svgIcon",
				(BiConsumer<MasterUrl, String>)MasterUrl::setSvgIcon);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<MasterUrl, Long>)MasterUrl::setUserId);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<MasterUrl, Long>)MasterUrl::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<MasterUrl, Long>)MasterUrl::setCompanyId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<MasterUrl, Date>)MasterUrl::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<MasterUrl, Date>)MasterUrl::setModifiedDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getMasterUrlId() {
		return _masterUrlId;
	}

	@Override
	public void setMasterUrlId(long masterUrlId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_masterUrlId = masterUrlId;
	}

	@JSON
	@Override
	public String getAppName() {
		if (_appName == null) {
			return "";
		}
		else {
			return _appName;
		}
	}

	@Override
	public void setAppName(String appName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appName = appName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalAppName() {
		return getColumnOriginalValue("appName");
	}

	@JSON
	@Override
	public String getBaseUrl() {
		if (_baseUrl == null) {
			return "";
		}
		else {
			return _baseUrl;
		}
	}

	@Override
	public void setBaseUrl(String baseUrl) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_baseUrl = baseUrl;
	}

	@JSON
	@Override
	public String getSvgIcon() {
		if (_svgIcon == null) {
			return "";
		}
		else {
			return _svgIcon;
		}
	}

	@Override
	public void setSvgIcon(String svgIcon) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_svgIcon = svgIcon;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(MasterUrl.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), MasterUrl.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MasterUrl toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, MasterUrl>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MasterUrlImpl masterUrlImpl = new MasterUrlImpl();

		masterUrlImpl.setUuid(getUuid());
		masterUrlImpl.setMasterUrlId(getMasterUrlId());
		masterUrlImpl.setAppName(getAppName());
		masterUrlImpl.setBaseUrl(getBaseUrl());
		masterUrlImpl.setSvgIcon(getSvgIcon());
		masterUrlImpl.setUserId(getUserId());
		masterUrlImpl.setGroupId(getGroupId());
		masterUrlImpl.setCompanyId(getCompanyId());
		masterUrlImpl.setCreateDate(getCreateDate());
		masterUrlImpl.setModifiedDate(getModifiedDate());

		masterUrlImpl.resetOriginalValues();

		return masterUrlImpl;
	}

	@Override
	public MasterUrl cloneWithOriginalValues() {
		MasterUrlImpl masterUrlImpl = new MasterUrlImpl();

		masterUrlImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		masterUrlImpl.setMasterUrlId(
			this.<Long>getColumnOriginalValue("masterUrlId"));
		masterUrlImpl.setAppName(
			this.<String>getColumnOriginalValue("appName"));
		masterUrlImpl.setBaseUrl(
			this.<String>getColumnOriginalValue("baseUrl"));
		masterUrlImpl.setSvgIcon(
			this.<String>getColumnOriginalValue("svgIcon"));
		masterUrlImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		masterUrlImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		masterUrlImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		masterUrlImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		masterUrlImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));

		return masterUrlImpl;
	}

	@Override
	public int compareTo(MasterUrl masterUrl) {
		long primaryKey = masterUrl.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof MasterUrl)) {
			return false;
		}

		MasterUrl masterUrl = (MasterUrl)object;

		long primaryKey = masterUrl.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<MasterUrl> toCacheModel() {
		MasterUrlCacheModel masterUrlCacheModel = new MasterUrlCacheModel();

		masterUrlCacheModel.uuid = getUuid();

		String uuid = masterUrlCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			masterUrlCacheModel.uuid = null;
		}

		masterUrlCacheModel.masterUrlId = getMasterUrlId();

		masterUrlCacheModel.appName = getAppName();

		String appName = masterUrlCacheModel.appName;

		if ((appName != null) && (appName.length() == 0)) {
			masterUrlCacheModel.appName = null;
		}

		masterUrlCacheModel.baseUrl = getBaseUrl();

		String baseUrl = masterUrlCacheModel.baseUrl;

		if ((baseUrl != null) && (baseUrl.length() == 0)) {
			masterUrlCacheModel.baseUrl = null;
		}

		masterUrlCacheModel.svgIcon = getSvgIcon();

		String svgIcon = masterUrlCacheModel.svgIcon;

		if ((svgIcon != null) && (svgIcon.length() == 0)) {
			masterUrlCacheModel.svgIcon = null;
		}

		masterUrlCacheModel.userId = getUserId();

		masterUrlCacheModel.groupId = getGroupId();

		masterUrlCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			masterUrlCacheModel.createDate = createDate.getTime();
		}
		else {
			masterUrlCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			masterUrlCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			masterUrlCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return masterUrlCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MasterUrl, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MasterUrl, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MasterUrl, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((MasterUrl)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, MasterUrl>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					MasterUrl.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _masterUrlId;
	private String _appName;
	private String _baseUrl;
	private String _svgIcon;
	private long _userId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<MasterUrl, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((MasterUrl)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("masterUrlId", _masterUrlId);
		_columnOriginalValues.put("appName", _appName);
		_columnOriginalValues.put("baseUrl", _baseUrl);
		_columnOriginalValues.put("svgIcon", _svgIcon);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("masterUrlId", 2L);

		columnBitmasks.put("appName", 4L);

		columnBitmasks.put("baseUrl", 8L);

		columnBitmasks.put("svgIcon", 16L);

		columnBitmasks.put("userId", 32L);

		columnBitmasks.put("groupId", 64L);

		columnBitmasks.put("companyId", 128L);

		columnBitmasks.put("createDate", 256L);

		columnBitmasks.put("modifiedDate", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private MasterUrl _escapedModel;

}